// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/Wei-Shaw/sub2api/ent"
	"github.com/Wei-Shaw/sub2api/internal/config"
	"github.com/Wei-Shaw/sub2api/internal/gateway"
	"github.com/Wei-Shaw/sub2api/internal/handler"
	"github.com/Wei-Shaw/sub2api/internal/handler/admin"
	"github.com/Wei-Shaw/sub2api/internal/plugin"
	"github.com/Wei-Shaw/sub2api/internal/repository"
	"github.com/Wei-Shaw/sub2api/internal/server"
	"github.com/Wei-Shaw/sub2api/internal/server/middleware"
	"github.com/Wei-Shaw/sub2api/internal/service"
	"github.com/redis/go-redis/v9"
	"log"
	"log/slog"
	"net/http"
	"sync"
	"time"
)

import (
	_ "embed"
	_ "github.com/Wei-Shaw/sub2api/ent/runtime"
)

// providePluginConfig 把核心 config.PluginConfig 翻译成 plugin.Config。
// 当 cfg.Plugins.Enabled=false 时,此 provider 仍会返回有效配置,
// 由 providePluginManager 决定是否真正实例化 manager。
func providePluginConfig(cfg *config.Config) plugin.Config {
	pc := cfg.Plugins
	out := plugin.DefaultConfig()
	out.BuiltinDir = pc.BuiltinDir
	out.PluginsDir = pc.Dir
	out.AutoEnableBuiltin = pc.AutoEnableBuiltin
	// V5 W5: reuse the host's existing 32-byte AES master key for plugin
	// SecretEncryption derivations. The host validates the key length /
	// hex shape during config load (see internal/config/config.go).
	out.SecretEncryptionMasterKeyHex = cfg.Totp.EncryptionKey
	if pc.HealthInterval > 0 {
		out.HealthInterval = time.Duration(pc.HealthInterval) * time.Second
	}
	if pc.ShutdownTimeout > 0 {
		out.ShutdownTimeout = time.Duration(pc.ShutdownTimeout) * time.Second
	}
	if pc.Restart.MaxRetries > 0 {
		out.Restart.MaxRetries = pc.Restart.MaxRetries
	}
	if pc.Restart.MaxDelay > 0 {
		out.Restart.MaxDelay = time.Duration(pc.Restart.MaxDelay) * time.Second
	}
	if pc.Restart.ResetAfter > 0 {
		out.Restart.ResetAfter = time.Duration(pc.Restart.ResetAfter) * time.Second
	}
	return out
}

// providePluginManager 创建 PluginManager,在 plugins.enabled=false 时返回 nil。
// 调用方(handler/frontend)需兼容 nil 情况。
//
// 注:此 provider 不接受 PluginRouter,因为 router 依赖 engine,
// engine 又依赖 handlers (含 pluginHandler),会形成循环依赖。
// router 由 wire 树构建完成后通过 BindRouter 后绑定。
func providePluginManager(
	cfg *config.Config,
	entClient *ent.Client,
	rdb *redis.Client,
	pluginCfg plugin.Config,
) (*plugin.PluginManager, error) {
	if !cfg.Plugins.Enabled {
		return nil, nil
	}
	db, err := repository.ProvideSQLDB(entClient)
	if err != nil {
		return nil, err
	}
	return plugin.NewPluginManager(db, rdb, pluginCfg, nil)
}

// Injectors from wire.go:

func initializeApplication(buildInfo handler.BuildInfo) (*Application, error) {
	configConfig, err := config.ProvideConfig()
	if err != nil {
		return nil, err
	}
	client, err := repository.ProvideEnt(configConfig)
	if err != nil {
		return nil, err
	}
	db, err := repository.ProvideSQLDB(client)
	if err != nil {
		return nil, err
	}
	userRepository := repository.NewUserRepository(client, db)
	redeemCodeRepository := repository.NewRedeemCodeRepository(client)
	redisClient := repository.ProvideRedis(configConfig)
	refreshTokenCache := repository.NewRefreshTokenCache(redisClient)
	settingRepository := repository.NewSettingRepository(client)
	groupRepository := repository.NewGroupRepository(client, db)
	proxyRepository := repository.NewProxyRepository(client, db)
	settingService := service.ProvideSettingService(settingRepository, groupRepository, proxyRepository, configConfig)
	rectifierSettingsCache := repository.NewRectifierSettingsCache(redisClient)
	settingService.SetRectifierSettingsCache(rectifierSettingsCache)
	emailCache := repository.NewEmailCache(redisClient)
	emailService := service.NewEmailService(settingRepository, emailCache)
	turnstileVerifier := repository.NewTurnstileVerifier()
	turnstileService := service.NewTurnstileService(settingService, turnstileVerifier)
	emailQueueService := service.ProvideEmailQueueService(emailService)
	promoCodeRepository := repository.NewPromoCodeRepository(client)
	billingCache := repository.NewBillingCache(redisClient)
	userSubscriptionRepository := repository.NewUserSubscriptionRepository(client)
	apiKeyRepository := repository.NewAPIKeyRepository(client, db)
	userRPMCache := repository.NewUserRPMCache(redisClient)
	userGroupRateRepository := repository.NewUserGroupRateRepository(db)
	serviceQuotaRuleRepository := repository.NewServiceQuotaRuleRepository(db)
	serviceQuotaLimiter := repository.NewServiceQuotaLimiter(redisClient)
	serviceQuotaCache := repository.NewServiceQuotaCache(redisClient)
	serviceQuotaService := service.ProvideServiceQuotaService(serviceQuotaRuleRepository, settingService, serviceQuotaLimiter, serviceQuotaCache, userRepository)
	userPlatformQuotaRepoImpl := repository.NewUserPlatformQuotaRepository(client)
	userPlatformQuotaRepo := repository.NewUserPlatformQuotaServiceAdapter(userPlatformQuotaRepoImpl)
	billingCacheService := service.ProvideBillingCacheService(billingCache, userRepository, userSubscriptionRepository, apiKeyRepository, userRPMCache, userGroupRateRepository, configConfig, userPlatformQuotaRepo, serviceQuotaService)
	apiKeyCache := repository.NewAPIKeyCache(redisClient)
	apiKeyService := service.ProvideAPIKeyService(apiKeyRepository, userRepository, groupRepository, userSubscriptionRepository, userGroupRateRepository, apiKeyCache, configConfig, billingCacheService)
	apiKeyAuthCacheInvalidator := service.ProvideAPIKeyAuthCacheInvalidator(apiKeyService)
	promoService := service.NewPromoService(promoCodeRepository, userRepository, billingCacheService, client, apiKeyAuthCacheInvalidator)
	subscriptionService := service.NewSubscriptionService(groupRepository, userSubscriptionRepository, billingCacheService, client, configConfig)
	affiliateRepository := repository.NewAffiliateRepository(client, db)
	affiliateService := service.NewAffiliateService(affiliateRepository, settingService, apiKeyAuthCacheInvalidator, billingCacheService)
	authService := service.NewAuthService(client, userRepository, redeemCodeRepository, refreshTokenCache, configConfig, settingService, emailService, turnstileService, emailQueueService, promoService, subscriptionService, affiliateService)
	userService := service.NewUserService(userRepository, settingRepository, apiKeyAuthCacheInvalidator, billingCache)
	redeemCache := repository.NewRedeemCache(redisClient)
	redeemService := service.NewRedeemService(redeemCodeRepository, userRepository, subscriptionService, redeemCache, billingCacheService, client, apiKeyAuthCacheInvalidator, affiliateService)
	secretEncryptor, err := repository.NewAESEncryptor(configConfig)
	if err != nil {
		return nil, err
	}
	totpCache := repository.NewTotpCache(redisClient)
	totpService := service.NewTotpService(userRepository, secretEncryptor, totpCache, settingService, emailService, emailQueueService)
	authHandler := handler.NewAuthHandler(configConfig, authService, userService, settingService, promoService, redeemService, totpService)
	userHandler := handler.NewUserHandler(userService, authService, emailService, emailCache, affiliateService, nil)
	apiKeyHandler := handler.NewAPIKeyHandler(apiKeyService)
	usageLogRepository := repository.NewUsageLogRepository(client, db)
	usageService := service.NewUsageService(usageLogRepository, userRepository, client, apiKeyAuthCacheInvalidator)
	redeemHandler := handler.NewRedeemHandler(redeemService)
	subscriptionHandler := handler.NewSubscriptionHandler(subscriptionService)
	announcementRepository := repository.NewAnnouncementRepository(client)
	announcementReadRepository := repository.NewAnnouncementReadRepository(client)
	announcementService := service.NewAnnouncementService(announcementRepository, announcementReadRepository, userRepository, userSubscriptionRepository)
	announcementHandler := handler.NewAnnouncementHandler(announcementService)
	// channelMonitorRepository / channelMonitorService / channelMonitorUserHandler 已迁移到 plugins/channel-management/
	dashboardAggregationRepository := repository.NewDashboardAggregationRepository(db)
	dashboardStatsCache := repository.NewDashboardCache(redisClient, configConfig)
	dashboardService := service.NewDashboardService(usageLogRepository, dashboardAggregationRepository, dashboardStatsCache, configConfig)
	timingWheelService, err := service.ProvideTimingWheelService()
	if err != nil {
		return nil, err
	}
	leaderLockCache := repository.NewLeaderLockCache(redisClient)
	dashboardAggregationService := service.ProvideDashboardAggregationService(dashboardAggregationRepository, timingWheelService, leaderLockCache, db, configConfig)
	dashboardHandler := admin.NewDashboardHandler(dashboardService, dashboardAggregationService)
	schedulerCache := repository.ProvideSchedulerCache(redisClient, configConfig)
	accountRepository := repository.NewAccountRepository(client, db, schedulerCache)
	proxyExitInfoProber := repository.NewProxyExitInfoProber(configConfig)
	proxyLatencyCache := repository.NewProxyLatencyCache(redisClient)
	privacyClientFactory := providePrivacyClientFactory()
	adminService := service.NewAdminService(userRepository, groupRepository, accountRepository, proxyRepository, apiKeyRepository, redeemCodeRepository, userGroupRateRepository, userRPMCache, billingCacheService, proxyExitInfoProber, proxyLatencyCache, apiKeyAuthCacheInvalidator, client, settingService, subscriptionService, userSubscriptionRepository, privacyClientFactory, nil)
	concurrencyCache := repository.ProvideConcurrencyCache(redisClient, configConfig)
	concurrencyService := service.ProvideConcurrencyService(concurrencyCache, accountRepository, configConfig)
	adminUserHandler := admin.NewUserHandler(adminService, concurrencyService, serviceQuotaService, userPlatformQuotaRepo, billingCacheService)
	sessionLimitCache := repository.ProvideSessionLimitCache(redisClient, configConfig)
	rpmCache := repository.NewRPMCache(redisClient)
	groupCapacityService := service.NewGroupCapacityService(accountRepository, groupRepository, concurrencyService, sessionLimitCache, rpmCache)
	groupHandler := admin.NewGroupHandler(adminService, dashboardService, groupCapacityService, serviceQuotaService)
	claudeOAuthClient := repository.NewClaudeOAuthClient()
	oAuthService := service.NewOAuthService(proxyRepository, claudeOAuthClient)
	openAIOAuthClient := repository.NewOpenAIOAuthClient()
	openAIOAuthService := service.NewOpenAIOAuthService(proxyRepository, openAIOAuthClient)
	geminiOAuthClient := repository.NewGeminiOAuthClient(configConfig)
	geminiCliCodeAssistClient := repository.NewGeminiCliCodeAssistClient()
	driveClient := repository.NewGeminiDriveClient()
	geminiOAuthService := service.NewGeminiOAuthService(proxyRepository, geminiOAuthClient, geminiCliCodeAssistClient, driveClient, configConfig)
	antigravityOAuthService := service.NewAntigravityOAuthService(proxyRepository)
	geminiQuotaService := service.NewGeminiQuotaService(configConfig, settingRepository)
	tempUnschedCache := repository.NewTempUnschedCache(redisClient)
	timeoutCounterCache := repository.NewTimeoutCounterCache(redisClient)
	openAI403CounterCache := repository.NewOpenAI403CounterCache(redisClient)
	geminiTokenCache := repository.NewGeminiTokenCache(redisClient)
	compositeTokenCacheInvalidator := service.NewCompositeTokenCacheInvalidator(geminiTokenCache)
	rateLimitService := service.ProvideRateLimitService(accountRepository, usageLogRepository, configConfig, geminiQuotaService, tempUnschedCache, timeoutCounterCache, openAI403CounterCache, settingService, compositeTokenCacheInvalidator)
	identityCache := repository.NewIdentityCache(redisClient)
	identityService := service.NewIdentityService(identityCache)
	httpUpstream := repository.NewHTTPUpstream(configConfig)
	claudeUsageFetcher := repository.NewClaudeUsageFetcher(httpUpstream)
	antigravityQuotaFetcher := service.NewAntigravityQuotaFetcher(proxyRepository)
	usageCache := service.NewUsageCache()
	tlsFingerprintProfileRepository := repository.NewTLSFingerprintProfileRepository(client)
	tlsFingerprintProfileCache := repository.NewTLSFingerprintProfileCache(redisClient)
	tlsFingerprintProfileService := service.NewTLSFingerprintProfileService(tlsFingerprintProfileRepository, tlsFingerprintProfileCache)
	accountUsageService := service.NewAccountUsageService(accountRepository, usageLogRepository, claudeUsageFetcher, geminiQuotaService, antigravityQuotaFetcher, usageCache, identityCache, tlsFingerprintProfileService)
	oAuthRefreshAPI := service.ProvideOAuthRefreshAPI(accountRepository, geminiTokenCache)
	geminiTokenProvider := service.ProvideGeminiTokenProvider(accountRepository, geminiTokenCache, geminiOAuthService, oAuthRefreshAPI)
	claudeTokenProvider := service.ProvideClaudeTokenProvider(accountRepository, geminiTokenCache, oAuthService, oAuthRefreshAPI)
	gatewayCache := repository.NewGatewayCache(redisClient)
	schedulerOutboxRepository := repository.NewSchedulerOutboxRepository(db)
	schedulerSnapshotService := service.ProvideSchedulerSnapshotService(schedulerCache, schedulerOutboxRepository, accountRepository, groupRepository, configConfig)
	antigravityTokenProvider := service.ProvideAntigravityTokenProvider(accountRepository, geminiTokenCache, antigravityOAuthService, oAuthRefreshAPI, tempUnschedCache)
	internal500CounterCache := repository.NewInternal500CounterCache(redisClient)
	antigravityGatewayService := service.NewAntigravityGatewayService(accountRepository, gatewayCache, schedulerSnapshotService, antigravityTokenProvider, rateLimitService, httpUpstream, settingService, internal500CounterCache, accountUsageService)
	accountTestService := service.NewAccountTestService(accountRepository, geminiTokenProvider, claudeTokenProvider, antigravityGatewayService, httpUpstream, configConfig, tlsFingerprintProfileService)
	crsSyncService := service.NewCRSSyncService(accountRepository, proxyRepository, configConfig)
	accountHandler := admin.NewAccountHandler(adminService, rateLimitService, accountUsageService, accountTestService, concurrencyService, crsSyncService, sessionLimitCache, rpmCache, compositeTokenCacheInvalidator, serviceQuotaService, nil)
	adminAnnouncementHandler := admin.NewAnnouncementHandler(announcementService)
	dataManagementService := service.NewDataManagementService()
	dataManagementHandler := admin.NewDataManagementHandler(dataManagementService)
	backupObjectStoreFactory := repository.NewS3BackupStoreFactory()
	dbDumper := repository.NewPgDumper(configConfig)
	backupService := service.ProvideBackupService(settingRepository, configConfig, secretEncryptor, backupObjectStoreFactory, dbDumper)
	backupHandler := admin.NewBackupHandler(backupService, userService)
	oAuthHandler := admin.NewOAuthHandler(oAuthService)
	proxyHandler := admin.NewProxyHandler(adminService)
	adminRedeemHandler := admin.NewRedeemHandler(adminService, redeemService)
	promoHandler := admin.NewPromoHandler(promoService)
	opsRepository := repository.NewOpsRepository(db)
	usageBillingRepository := repository.NewUsageBillingRepository(client, db)
	pricingRemoteClient := repository.ProvidePricingRemoteClient(configConfig)
	pricingService, err := service.ProvidePricingService(configConfig, pricingRemoteClient)
	if err != nil {
		return nil, err
	}
	billingService := service.NewBillingService(configConfig, pricingService)
	deferredService := service.ProvideDeferredService(accountRepository, timingWheelService)
	digestSessionStore := service.NewDigestSessionStore()
	// channel-management 已迁移到插件；网关侧通过 Redis 读取渠道缓存
	pricingOverrideCache := service.NewPricingOverrideCache()
	channelCacheReader := service.NewChannelCacheReader(redisClient, pricingOverrideCache)
	modelPricingResolver := service.NewModelPricingResolver(channelCacheReader, billingService)
	balanceNotifyService := service.NewBalanceNotifyService(emailService, settingRepository, accountRepository)
	gatewayService := service.NewGatewayService(accountRepository, groupRepository, usageLogRepository, usageBillingRepository, userRepository, userSubscriptionRepository, userGroupRateRepository, gatewayCache, configConfig, schedulerSnapshotService, concurrencyService, billingService, rateLimitService, billingCacheService, identityService, httpUpstream, deferredService, claudeTokenProvider, sessionLimitCache, rpmCache, digestSessionStore, settingService, tlsFingerprintProfileService, channelCacheReader, modelPricingResolver, balanceNotifyService)
	// Wire the Antigravity INTERNAL 500 progressive penalty into the gateway
	// pipeline's failure/success hooks (the legacy in-service Forward loop that
	// owned this logic is bypassed by the plugin gateway path).
	gatewayService.SetInternal500PenaltyHook(antigravityGatewayService)
	openAITokenProvider := service.ProvideOpenAITokenProvider(accountRepository, geminiTokenCache, openAIOAuthService, oAuthRefreshAPI)
	openAIGatewayService := service.NewOpenAIGatewayService(accountRepository, usageLogRepository, usageBillingRepository, userRepository, userSubscriptionRepository, userGroupRateRepository, gatewayCache, configConfig, schedulerSnapshotService, concurrencyService, billingService, rateLimitService, billingCacheService, httpUpstream, deferredService, openAITokenProvider, modelPricingResolver, channelCacheReader, balanceNotifyService, settingService)
	geminiMessagesCompatService := service.NewGeminiMessagesCompatService(accountRepository, groupRepository, gatewayCache, schedulerSnapshotService, geminiTokenProvider, rateLimitService, httpUpstream, antigravityGatewayService, configConfig)
	// Gateway Pipeline: empty ProviderRegistry populated dynamically by plugins at spawn time.
	providerRegistry := gateway.ProvideProviderRegistry()
	gatewayPipeline := gateway.ProvideGatewayPipeline(providerRegistry, gatewayService, billingCacheService, concurrencyService, settingService, configConfig)
	opsRetryForwarder := gateway.ProvideOpsRetryForwarder(providerRegistry)
	opsSystemLogSink := service.ProvideOpsSystemLogSink(opsRepository)
	opsService := service.NewOpsService(opsRepository, settingRepository, configConfig, accountRepository, userRepository, concurrencyService, gatewayService, opsRetryForwarder, opsSystemLogSink)
	usageHandler := handler.NewUsageHandler(usageService, apiKeyService, opsService, settingService)
	// payment registry / encryptionKey / paymentConfigService / paymentService 已迁移到 plugins/payment/
	settingHandler := admin.NewSettingHandler(settingService, emailService, turnstileService, opsService, serviceQuotaService)
	opsHandler := admin.NewOpsHandler(opsService)
	updateCache := repository.NewUpdateCache(redisClient)
	gitHubReleaseClient := repository.ProvideGitHubReleaseClient(configConfig)
	serviceBuildInfo := provideServiceBuildInfo(buildInfo)
	updateService := service.ProvideUpdateService(updateCache, gitHubReleaseClient, serviceBuildInfo)
	idempotencyRepository := repository.NewIdempotencyRepository(client, db)
	systemOperationLockService := service.ProvideSystemOperationLockService(idempotencyRepository, configConfig)
	systemHandler := handler.ProvideSystemHandler(updateService, systemOperationLockService)
	adminSubscriptionHandler := admin.NewSubscriptionHandler(subscriptionService)
	usageCleanupRepository := repository.NewUsageCleanupRepository(client, db)
	usageCleanupService := service.ProvideUsageCleanupService(usageCleanupRepository, timingWheelService, dashboardAggregationService, configConfig)
	adminUsageHandler := admin.NewUsageHandler(usageService, apiKeyService, adminService, usageCleanupService)
	userAttributeDefinitionRepository := repository.NewUserAttributeDefinitionRepository(client)
	userAttributeValueRepository := repository.NewUserAttributeValueRepository(client)
	userAttributeService := service.NewUserAttributeService(userAttributeDefinitionRepository, userAttributeValueRepository)
	userAttributeHandler := admin.NewUserAttributeHandler(userAttributeService)
	errorPassthroughRepository := repository.NewErrorPassthroughRepository(client)
	errorPassthroughCache := repository.NewErrorPassthroughCache(redisClient)
	errorPassthroughService := service.NewErrorPassthroughService(errorPassthroughRepository, errorPassthroughCache)
	errorPassthroughHandler := admin.NewErrorPassthroughHandler(errorPassthroughService)
	tlsFingerprintProfileHandler := admin.NewTLSFingerprintProfileHandler(tlsFingerprintProfileService)
	adminAPIKeyHandler := admin.NewAdminAPIKeyHandler(adminService)
	scheduledTestPlanRepository := repository.NewScheduledTestPlanRepository(db)
	scheduledTestResultRepository := repository.NewScheduledTestResultRepository(db)
	scheduledTestService := service.ProvideScheduledTestService(scheduledTestPlanRepository, scheduledTestResultRepository)
	scheduledTestHandler := admin.NewScheduledTestHandler(scheduledTestService)
	// channelHandler / channelMonitorHandler / channelMonitorRequestTemplateHandler: 已迁移到 plugins/channel-management/
	// paymentHandler / paymentOrderExpiryService 已迁移到 plugins/payment/
	// contentModerationRepository / contentModerationHashCache / contentModerationService / contentModerationHandler 已迁移到 plugins/content-moderation/
	serviceQuotaHandler := admin.NewServiceQuotaHandler(serviceQuotaService)
	serviceQuotaMonitorService := service.NewServiceQuotaMonitorService(serviceQuotaRuleRepository, serviceQuotaLimiter, serviceQuotaCache, settingService)
	serviceQuotaMonitorHandler := admin.NewServiceQuotaMonitorHandler(serviceQuotaMonitorService)
	pluginConfig := providePluginConfig(configConfig)
	pluginManager, err := providePluginManager(configConfig, client, redisClient, pluginConfig)
	if err != nil {
		return nil, err
	}
	pluginHandler := handler.ProvidePluginHandler(pluginManager)
	pluginSettingsService := service.NewPluginSettingsService(db)
	if pluginManager != nil {
		accountHandler.SetPlatformRegistry(pluginManager.PlatformRegistry())
		oAuthHandler.SetPlatformRegistry(pluginManager.PlatformRegistry())
		// Inject the plugin-backed compatible platform resolver so the
		// scheduler uses PlatformDecl.CompatibleGateways instead of
		// hardcoded Antigravity rules.
		gatewayService.SetCompatiblePlatformResolver(pluginManager.PlatformRegistry())
		schedulerSnapshotService.SetCompatiblePlatformResolver(pluginManager.PlatformRegistry())
		adminService.SetCompatiblePlatformResolver(pluginManager.PlatformRegistry())
	}
	pluginSettingsHandler := handler.ProvidePluginSettingsHandler(pluginSettingsService)
	if pluginManager != nil {
		pluginManager.SetSettings(pluginSettingsService, func(resolver func(ctx context.Context) string) plugin.SettingsExtensionRegistrar {
			return plugin.NewSettingsExtensionServer(pluginSettingsService, resolver)
		})
		// PublicFlags resolution shares the same store SDK Settings writes
		// through so /api/v1/settings/public reflects live admin edits without
		// a manager restart. See manager_public_flags.go for the contract.
		pluginManager.SetPluginSettingsReader(pluginSettingsService)
		settingService.SetPluginPublicFlagProvider(pluginManager)
	}
	if pluginManager != nil {
		// Plugin Hook Phase B: register the event publisher with the plugin
		// manager (so the EventsExtension gRPC service is wired) and inject
		// the same publisher into every business service that emits events.
		pluginEventPublisher := plugin.NewEventPublisher(slog.Default())
		pluginManager.SetEvents(pluginEventPublisher)
		// paymentService.SetPluginEventPublisher: payment service 已迁移到 plugin
		authService.SetPluginEventPublisher(pluginEventPublisher)
		antigravityGatewayService.SetPluginEventPublisher(pluginEventPublisher)
		rateLimitService.SetPluginEventPublisher(pluginEventPublisher)
	}
	if pluginManager != nil {
		// P3+P5 PricingExtension wire: feed the host-wide PricingOverrideCache
		// (consumed by ChannelCacheReader's fast path) plus the BillingService
		// adjuster seam so plugins implementing PricingExtension can
		// participate without further wiring.
		pluginManager.SetPricingExtension(pricingOverrideCache, billingService)
		// AccountStats resolver hook: GatewayService + OpenAIGatewayService
		// both consult the plugin per-request to compute usage_logs.account_stats_cost.
		// One adapter forwards to both so the channel-management plugin
		// covers Anthropic and OpenAI gateways uniformly.
		pluginManager.SetAccountStatsResolverRegistrar(&accountStatsResolverFanout{
			gateway:       gatewayService,
			openaiGateway: openAIGatewayService,
		})
		// Model support checker hook: let plugins override the static
		// account.IsModelSupported check during scheduling.
		pluginManager.SetModelSupportCheckerRegistrar(&modelSupportCheckerFanout{
			gateway: gatewayService,
		})
		// Scheduling hints hook: let plugins dynamically adjust account
		// priority and availability during scheduling.
		pluginManager.SetSchedulingHintsRegistrar(&schedulingHintsFanout{
			gateway: gatewayService,
		})
		// Schedulability checker hook: let plugins inject custom
		// schedulability checks during account selection.
		pluginManager.SetSchedulabilityCheckerRegistrar(&schedulabilityCheckerFanout{
			gateway: gatewayService,
		})
		// HostService wire (ADR-UPSTREAM-SYNC-115-121 §4): let plugins call
		// BillingService.GetModelPricing over the reverse gRPC channel so
		// channel-management can render a global-pricing fallback for the
		// "Available Channels" popover without vendoring LiteLLM data.
		pluginManager.SetHostPricingResolver(billingService)
		// Phase 0 payment-plugin migration: SQL-backed idempotency store
		// dedupes externally-retried HostService writes (CreditBalance /
		// AssignSubscription / AccrueRebate / …). Adapters wrap the host
		// repos / services with that store so a payment plugin can call
		// the host without risking double-credit on retry.
		hostIdempotencyStore := plugin.NewHostIdempotencyStore(db)
		pluginManager.SetHostBalanceService(plugin.NewHostBalanceAdapter(userRepository, hostIdempotencyStore))
		pluginManager.SetHostSubscriptionAssigner(plugin.NewHostSubscriptionAdapter(subscriptionService, hostIdempotencyStore))
		pluginManager.SetHostAffiliateAccruer(plugin.NewHostAffiliateAdapter(affiliateService, hostIdempotencyStore))
		pluginManager.SetHostUserLookup(plugin.NewHostUserLookupAdapter(userRepository, affiliateService))
	}
	if pluginManager != nil {
		// Gateway provider registry: let plugins register as gateway
		// providers so plugin-backed platforms appear in ProviderRegistry
		// alongside the three built-in adapters (Anthropic/OpenAI/Antigravity).
		gatewayAdapter := gateway.NewPluginRegistryAdapter(providerRegistry, slog.Default())
		pluginManager.SetGatewayProviderRegistry(gatewayAdapter)
		pluginManager.SetPipeline(gatewayPipeline)
	}
	affiliateHandler := admin.NewAffiliateHandler(affiliateService, adminService)
	uploadService := service.ProvideUploadService(configConfig)
	adminUploadHandler := admin.NewUploadHandler(uploadService)
	complianceHandler := admin.NewComplianceHandler(settingService)
	platformHandler := handler.ProvidePlatformHandler(pluginManager)
	adminHandlers := handler.ProvideAdminHandlers(dashboardHandler, adminUserHandler, groupHandler, accountHandler, adminAnnouncementHandler, dataManagementHandler, backupHandler, oAuthHandler, proxyHandler, adminRedeemHandler, promoHandler, settingHandler, opsHandler, systemHandler, adminSubscriptionHandler, adminUsageHandler, userAttributeHandler, errorPassthroughHandler, tlsFingerprintProfileHandler, adminAPIKeyHandler, scheduledTestHandler, serviceQuotaHandler, serviceQuotaMonitorHandler, affiliateHandler, complianceHandler, pluginHandler, pluginSettingsHandler, adminUploadHandler, platformHandler)
	usageRecordWorkerPool := service.NewUsageRecordWorkerPool(configConfig)
	userMsgQueueCache := repository.NewUserMsgQueueCache(redisClient)
	userMessageQueueService := service.ProvideUserMessageQueueService(userMsgQueueCache, rpmCache, configConfig)
	gatewayHandler := handler.NewGatewayHandler(gatewayService, handler.NewGeminiModelListingProvider(geminiMessagesCompatService), userService, concurrencyService, billingCacheService, usageService, apiKeyService, usageRecordWorkerPool, errorPassthroughService, userMessageQueueService, configConfig, settingService)
	openAIGatewayHandler := handler.NewOpenAIGatewayHandler(openAIGatewayService, concurrencyService, billingCacheService, apiKeyService, usageRecordWorkerPool, errorPassthroughService, configConfig)
	handlerSettingHandler := handler.ProvideSettingHandler(settingService, buildInfo)
	totpHandler := handler.NewTotpHandler(totpService)
	// PaymentHandler / PaymentWebhookHandler 已迁移到 plugins/payment/
	userServiceQuotaHandler := handler.NewUserServiceQuotaHandler(serviceQuotaMonitorService)
	idempotencyCoordinator := service.ProvideIdempotencyCoordinator(idempotencyRepository, configConfig)
	idempotencyCleanupService := service.ProvideIdempotencyCleanupService(idempotencyRepository, configConfig)
	uploadHandler := handler.NewUploadHandler(uploadService)
	handlers := handler.ProvideHandlers(authHandler, userHandler, apiKeyHandler, usageHandler, redeemHandler, subscriptionHandler, announcementHandler, adminHandlers, gatewayHandler, openAIGatewayHandler, handlerSettingHandler, totpHandler, userServiceQuotaHandler, uploadHandler, gatewayPipeline, idempotencyCoordinator, idempotencyCleanupService)
	jwtAuthMiddleware := middleware.NewJWTAuthMiddleware(authService, userService)
	adminAuthMiddleware := middleware.NewAdminAuthMiddleware(authService, userService, settingService)
	apiKeyAuthMiddleware := middleware.NewAPIKeyAuthMiddleware(apiKeyService, subscriptionService, configConfig)
	engine := server.ProvideRouter(configConfig, handlers, jwtAuthMiddleware, adminAuthMiddleware, apiKeyAuthMiddleware, apiKeyService, subscriptionService, opsService, settingService, redisClient, pluginManager)
	pluginRouter := server.ProvidePluginRouter(engine, jwtAuthMiddleware, adminAuthMiddleware, apiKeyAuthMiddleware, settingService)
	if pluginManager != nil {
		pluginManager.BindRouter(pluginRouter)
	}
	httpServer := server.ProvideHTTPServer(configConfig, engine, pluginRouter)
	opsMetricsCollector := service.ProvideOpsMetricsCollector(opsRepository, settingRepository, accountRepository, concurrencyService, db, redisClient, configConfig)
	opsAggregationService := service.ProvideOpsAggregationService(opsRepository, settingRepository, db, redisClient, configConfig)
	opsAlertEvaluatorService := service.ProvideOpsAlertEvaluatorService(opsService, opsRepository, emailService, redisClient, configConfig, proxyRepository)
	opsCleanupService := service.ProvideOpsCleanupService(opsRepository, db, redisClient, configConfig, settingRepository, opsService)
	if pluginManager != nil {
		opsCleanupService.SetPluginMaintenance(pluginManager)
	}
	opsScheduledReportService := service.ProvideOpsScheduledReportService(opsService, userService, emailService, redisClient, configConfig)
	tokenRefreshService := service.ProvideTokenRefreshService(accountRepository, compositeTokenCacheInvalidator, schedulerCache, configConfig, tempUnschedCache, privacyClientFactory, proxyRepository, oAuthRefreshAPI)
	// Inject plugin-based token refresher and start the service.
	// PluginManager is already initialized at this point.
	{
		var pluginRefresher service.PluginTokenRefresher
		if pluginManager != nil {
			pluginRefresher = plugin.NewPluginTokenRefresher(pluginManager.PlatformRegistry())
		} else {
			pluginRefresher = service.NoopPluginTokenRefresher()
		}
		tokenRefreshService.SetPluginTokenRefresher(pluginRefresher)
		crsSyncService.SetPluginTokenRefresher(pluginRefresher)
	}
	tokenRefreshService.Start()
	accountExpiryService := service.ProvideAccountExpiryService(accountRepository)
	proxyExpiryService := service.ProvideProxyExpiryService(proxyRepository)
	notificationEmailService := service.NewNotificationEmailService(settingRepository, emailService)
	balanceNotifyService.SetNotificationEmailService(notificationEmailService)
	subscriptionExpiryService := service.ProvideSubscriptionExpiryService(userSubscriptionRepository, settingRepository, notificationEmailService, leaderLockCache, db)
	scheduledTestRunnerService := service.ProvideScheduledTestRunnerService(scheduledTestPlanRepository, scheduledTestService, accountTestService, rateLimitService, configConfig)
	// channelMonitorRunner / paymentOrderExpiryService: 已迁移到插件
	quotaFlusher := service.ProvideUserPlatformQuotaUsageFlusher(configConfig, billingCache, userPlatformQuotaRepo, timingWheelService)
	v := provideCleanup(client, redisClient, opsMetricsCollector, opsAggregationService, opsAlertEvaluatorService, opsCleanupService, opsScheduledReportService, opsSystemLogSink, schedulerSnapshotService, tokenRefreshService, accountExpiryService, proxyExpiryService, subscriptionExpiryService, usageCleanupService, idempotencyCleanupService, pricingService, emailQueueService, billingCacheService, usageRecordWorkerPool, subscriptionService, oAuthService, openAIOAuthService, geminiOAuthService, antigravityOAuthService, openAIGatewayService, scheduledTestRunnerService, backupService, pluginManager, nil, quotaFlusher)
	application := &Application{
		Server:         httpServer,
		PluginManager:  pluginManager,
		Cfg:            configConfig,
		PluginSettings: pluginSettingsService,
		Cleanup:        v,
	}
	return application, nil
}

// wire.go:

type Application struct {
	Server        *http.Server
	PluginManager *plugin.PluginManager
	// Cfg is exposed so main.go can run host-side reconciliation steps
	// (e.g. BUG #64 payment resume signing-key backfill) that must read
	// the resolved configuration without re-loading it.
	Cfg *config.Config
	// PluginSettings is exposed for the same reason: main.go drives the
	// post-Start payment-plugin signing-key backfill via this service.
	PluginSettings *service.PluginSettingsService
	Cleanup        func()
}

func providePrivacyClientFactory() service.PrivacyClientFactory {
	return repository.CreatePrivacyReqClient
}

func provideServiceBuildInfo(buildInfo handler.BuildInfo) service.BuildInfo {
	return service.BuildInfo{
		Version:   buildInfo.Version,
		BuildType: buildInfo.BuildType,
	}
}

func provideCleanup(
	entClient *ent.Client,
	rdb *redis.Client,
	opsMetricsCollector *service.OpsMetricsCollector,
	opsAggregation *service.OpsAggregationService,
	opsAlertEvaluator *service.OpsAlertEvaluatorService,
	opsCleanup *service.OpsCleanupService,
	opsScheduledReport *service.OpsScheduledReportService,
	opsSystemLogSink *service.OpsSystemLogSink,
	schedulerSnapshot *service.SchedulerSnapshotService,
	tokenRefresh *service.TokenRefreshService,
	accountExpiry *service.AccountExpiryService,
	proxyExpiry *service.ProxyExpiryService,
	subscriptionExpiry *service.SubscriptionExpiryService,
	usageCleanup *service.UsageCleanupService,
	idempotencyCleanup *service.IdempotencyCleanupService,
	pricing *service.PricingService,
	emailQueue *service.EmailQueueService,
	billingCache *service.BillingCacheService,
	usageRecordWorkerPool *service.UsageRecordWorkerPool,
	subscriptionService *service.SubscriptionService,
	oauth *service.OAuthService,
	openaiOAuth *service.OpenAIOAuthService,
	geminiOAuth *service.GeminiOAuthService,
	antigravityOAuth *service.AntigravityOAuthService,
	openAIGateway *service.OpenAIGatewayService,
	scheduledTestRunner *service.ScheduledTestRunnerService,
	backupSvc *service.BackupService,
	pluginManager *plugin.PluginManager,
	channelMonitorRunner *service.ChannelMonitorRunner,
	quotaFlusher *service.UserPlatformQuotaUsageFlusher,
) func() {
	return func() {
		ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
		defer cancel()

		type cleanupStep struct {
			name string
			fn   func() error
		}

		parallelSteps := []cleanupStep{
			{"PluginManager", func() error {
				if pluginManager != nil {
					pluginManager.ShutdownAll(ctx)
				}
				return nil
			}},
			{"OpsScheduledReportService", func() error {
				if opsScheduledReport != nil {
					opsScheduledReport.Stop()
				}
				return nil
			}},
			{"OpsCleanupService", func() error {
				if opsCleanup != nil {
					opsCleanup.Stop()
				}
				return nil
			}},
			{"OpsSystemLogSink", func() error {
				if opsSystemLogSink != nil {
					opsSystemLogSink.Stop()
				}
				return nil
			}},
			{"OpsAlertEvaluatorService", func() error {
				if opsAlertEvaluator != nil {
					opsAlertEvaluator.Stop()
				}
				return nil
			}},
			{"OpsAggregationService", func() error {
				if opsAggregation != nil {
					opsAggregation.Stop()
				}
				return nil
			}},
			{"OpsMetricsCollector", func() error {
				if opsMetricsCollector != nil {
					opsMetricsCollector.Stop()
				}
				return nil
			}},
			{"SchedulerSnapshotService", func() error {
				if schedulerSnapshot != nil {
					schedulerSnapshot.Stop()
				}
				return nil
			}},
			{"UsageCleanupService", func() error {
				if usageCleanup != nil {
					usageCleanup.Stop()
				}
				return nil
			}},
			{"IdempotencyCleanupService", func() error {
				if idempotencyCleanup != nil {
					idempotencyCleanup.Stop()
				}
				return nil
			}},
			{"TokenRefreshService", func() error {
				tokenRefresh.Stop()
				return nil
			}},
			{"AccountExpiryService", func() error {
				accountExpiry.Stop()
				return nil
			}},
			{"ProxyExpiryService", func() error {
				proxyExpiry.Stop()
				return nil
			}},
			{"SubscriptionExpiryService", func() error {
				subscriptionExpiry.Stop()
				return nil
			}},
			{"SubscriptionService", func() error {
				if subscriptionService != nil {
					subscriptionService.Stop()
				}
				return nil
			}},
			{"PricingService", func() error {
				pricing.Stop()
				return nil
			}},
			{"EmailQueueService", func() error {
				emailQueue.Stop()
				return nil
			}},
			{"BillingCacheService", func() error {
				billingCache.Stop()
				return nil
			}},
			{"UsageRecordWorkerPool", func() error {
				if usageRecordWorkerPool != nil {
					usageRecordWorkerPool.Stop()
				}
				return nil
			}},
			{"OAuthService", func() error {
				oauth.Stop()
				return nil
			}},
			{"OpenAIOAuthService", func() error {
				openaiOAuth.Stop()
				return nil
			}},
			{"GeminiOAuthService", func() error {
				geminiOAuth.Stop()
				return nil
			}},
			{"AntigravityOAuthService", func() error {
				antigravityOAuth.Stop()
				return nil
			}},
			{"OpenAIWSPool", func() error {
				if openAIGateway != nil {
					openAIGateway.CloseOpenAIWSPool()
				}
				return nil
			}},
			{"ScheduledTestRunnerService", func() error {
				if scheduledTestRunner != nil {
					scheduledTestRunner.Stop()
				}
				return nil
			}},
			{"BackupService", func() error {
				if backupSvc != nil {
					backupSvc.Stop()
				}
				return nil
			}},
			// PaymentOrderExpiryService 已迁移到 plugins/payment/
			{"ChannelMonitorRunner", func() error {
				if channelMonitorRunner != nil {
					channelMonitorRunner.Stop()
				}
				return nil
			}},
			{"UserPlatformQuotaUsageFlusher", func() error {
				if quotaFlusher != nil {
					quotaFlusher.Stop()
				}
				return nil
			}},
		}

		infraSteps := []cleanupStep{
			{"Redis", func() error {
				if rdb == nil {
					return nil
				}
				return rdb.Close()
			}},
			{"Ent", func() error {
				if entClient == nil {
					return nil
				}
				return entClient.Close()
			}},
		}

		runParallel := func(steps []cleanupStep) {
			var wg sync.WaitGroup
			for i := range steps {
				step := steps[i]
				wg.Add(1)
				go func() {
					defer wg.Done()
					if err := step.fn(); err != nil {
						log.Printf("[Cleanup] %s failed: %v", step.name, err)
						return
					}
					log.Printf("[Cleanup] %s succeeded", step.name)
				}()
			}
			wg.Wait()
		}

		runSequential := func(steps []cleanupStep) {
			for i := range steps {
				step := steps[i]
				if err := step.fn(); err != nil {
					log.Printf("[Cleanup] %s failed: %v", step.name, err)
					continue
				}
				log.Printf("[Cleanup] %s succeeded", step.name)
			}
		}

		runParallel(parallelSteps)
		runSequential(infraSteps)

		select {
		case <-ctx.Done():
			log.Printf("[Cleanup] Warning: cleanup timed out after 10 seconds")
		default:
			log.Printf("[Cleanup] All cleanup steps completed")
		}
	}
}

// accountStatsResolverFanout adapts the plugin manager's
// AccountStatsResolverRegistrar to both gateway services. The adapter
// is hand-coded here (rather than via wire) because it is a small bridge
// between two singletons we want to keep in lockstep — installing the
// resolver on only one of them would silently leave the other gateway's
// usage_logs.account_stats_cost column NULL even when a plugin is
// active.
type accountStatsResolverFanout struct {
	gateway       *service.GatewayService
	openaiGateway *service.OpenAIGatewayService
}

// SetAccountStatsResolver forwards to both gateways. Both setters are
// concurrent-safe; either being nil (e.g. a stripped test build) is
// tolerated by guarding here.
func (a *accountStatsResolverFanout) SetAccountStatsResolver(resolver service.AccountStatsCostResolver) {
	if a == nil {
		return
	}
	if a.gateway != nil {
		a.gateway.SetAccountStatsResolver(resolver)
	}
	if a.openaiGateway != nil {
		a.openaiGateway.SetAccountStatsResolver(resolver)
	}
}

// modelSupportCheckerFanout forwards the plugin-backed model support
// checker to the GatewayService (and potentially OpenAIGatewayService
// in the future).
type modelSupportCheckerFanout struct {
	gateway *service.GatewayService
}

// SetPluginModelSupportChecker forwards to the gateway service.
func (f *modelSupportCheckerFanout) SetPluginModelSupportChecker(checker service.PluginModelSupportChecker) {
	if f == nil {
		return
	}
	if f.gateway != nil {
		f.gateway.SetPluginModelSupportChecker(checker)
	}
}

// schedulingHintsFanout forwards the plugin-backed scheduling hints
// provider to the GatewayService.
type schedulingHintsFanout struct {
	gateway *service.GatewayService
}

// SetPluginSchedulingHintsProvider forwards to the gateway service.
func (f *schedulingHintsFanout) SetPluginSchedulingHintsProvider(provider service.PluginSchedulingHintsProvider) {
	if f == nil {
		return
	}
	if f.gateway != nil {
		f.gateway.SetPluginSchedulingHintsProvider(provider)
	}
}

// schedulabilityCheckerFanout forwards the plugin-backed schedulability
// checker to the GatewayService.
type schedulabilityCheckerFanout struct {
	gateway *service.GatewayService
}

// SetPluginSchedulabilityChecker forwards to the gateway service.
func (f *schedulabilityCheckerFanout) SetPluginSchedulabilityChecker(checker service.PluginSchedulabilityChecker) {
	if f == nil {
		return
	}
	if f.gateway != nil {
		f.gateway.SetPluginSchedulabilityChecker(checker)
	}
}
