// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/plugin"
)

// Plugin is the model entity for the Plugin schema.
type Plugin struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Version holds the value of the "version" field.
	Version string `json:"version,omitempty"`
	// APIVersion holds the value of the "api_version" field.
	APIVersion string `json:"api_version,omitempty"`
	// State holds the value of the "state" field.
	State plugin.State `json:"state,omitempty"`
	// InstalledAt holds the value of the "installed_at" field.
	InstalledAt time.Time `json:"installed_at,omitempty"`
	// LastEnabledAt holds the value of the "last_enabled_at" field.
	LastEnabledAt *time.Time `json:"last_enabled_at,omitempty"`
	// DeclaredTables holds the value of the "declared_tables" field.
	DeclaredTables []string `json:"declared_tables,omitempty"`
	// MetaSnapshot holds the value of the "meta_snapshot" field.
	MetaSnapshot map[string]interface{} `json:"meta_snapshot,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Plugin) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case plugin.FieldDeclaredTables, plugin.FieldMetaSnapshot:
			values[i] = new([]byte)
		case plugin.FieldID, plugin.FieldVersion, plugin.FieldAPIVersion, plugin.FieldState:
			values[i] = new(sql.NullString)
		case plugin.FieldInstalledAt, plugin.FieldLastEnabledAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Plugin fields.
func (_m *Plugin) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case plugin.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case plugin.FieldVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value.Valid {
				_m.Version = value.String
			}
		case plugin.FieldAPIVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field api_version", values[i])
			} else if value.Valid {
				_m.APIVersion = value.String
			}
		case plugin.FieldState:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field state", values[i])
			} else if value.Valid {
				_m.State = plugin.State(value.String)
			}
		case plugin.FieldInstalledAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field installed_at", values[i])
			} else if value.Valid {
				_m.InstalledAt = value.Time
			}
		case plugin.FieldLastEnabledAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_enabled_at", values[i])
			} else if value.Valid {
				_m.LastEnabledAt = new(time.Time)
				*_m.LastEnabledAt = value.Time
			}
		case plugin.FieldDeclaredTables:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field declared_tables", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.DeclaredTables); err != nil {
					return fmt.Errorf("unmarshal field declared_tables: %w", err)
				}
			}
		case plugin.FieldMetaSnapshot:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field meta_snapshot", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.MetaSnapshot); err != nil {
					return fmt.Errorf("unmarshal field meta_snapshot: %w", err)
				}
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Plugin.
// This includes values selected through modifiers, order, etc.
func (_m *Plugin) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Plugin.
// Note that you need to call Plugin.Unwrap() before calling this method if this Plugin
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Plugin) Update() *PluginUpdateOne {
	return NewPluginClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Plugin entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Plugin) Unwrap() *Plugin {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Plugin is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Plugin) String() string {
	var builder strings.Builder
	builder.WriteString("Plugin(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("version=")
	builder.WriteString(_m.Version)
	builder.WriteString(", ")
	builder.WriteString("api_version=")
	builder.WriteString(_m.APIVersion)
	builder.WriteString(", ")
	builder.WriteString("state=")
	builder.WriteString(fmt.Sprintf("%v", _m.State))
	builder.WriteString(", ")
	builder.WriteString("installed_at=")
	builder.WriteString(_m.InstalledAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.LastEnabledAt; v != nil {
		builder.WriteString("last_enabled_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("declared_tables=")
	builder.WriteString(fmt.Sprintf("%v", _m.DeclaredTables))
	builder.WriteString(", ")
	builder.WriteString("meta_snapshot=")
	builder.WriteString(fmt.Sprintf("%v", _m.MetaSnapshot))
	builder.WriteByte(')')
	return builder.String()
}

// Plugins is a parsable slice of Plugin.
type Plugins []*Plugin
