// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/plugin"
)

// PluginCreate is the builder for creating a Plugin entity.
type PluginCreate struct {
	config
	mutation *PluginMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetVersion sets the "version" field.
func (_c *PluginCreate) SetVersion(v string) *PluginCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetAPIVersion sets the "api_version" field.
func (_c *PluginCreate) SetAPIVersion(v string) *PluginCreate {
	_c.mutation.SetAPIVersion(v)
	return _c
}

// SetState sets the "state" field.
func (_c *PluginCreate) SetState(v plugin.State) *PluginCreate {
	_c.mutation.SetState(v)
	return _c
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_c *PluginCreate) SetNillableState(v *plugin.State) *PluginCreate {
	if v != nil {
		_c.SetState(*v)
	}
	return _c
}

// SetInstalledAt sets the "installed_at" field.
func (_c *PluginCreate) SetInstalledAt(v time.Time) *PluginCreate {
	_c.mutation.SetInstalledAt(v)
	return _c
}

// SetNillableInstalledAt sets the "installed_at" field if the given value is not nil.
func (_c *PluginCreate) SetNillableInstalledAt(v *time.Time) *PluginCreate {
	if v != nil {
		_c.SetInstalledAt(*v)
	}
	return _c
}

// SetLastEnabledAt sets the "last_enabled_at" field.
func (_c *PluginCreate) SetLastEnabledAt(v time.Time) *PluginCreate {
	_c.mutation.SetLastEnabledAt(v)
	return _c
}

// SetNillableLastEnabledAt sets the "last_enabled_at" field if the given value is not nil.
func (_c *PluginCreate) SetNillableLastEnabledAt(v *time.Time) *PluginCreate {
	if v != nil {
		_c.SetLastEnabledAt(*v)
	}
	return _c
}

// SetDeclaredTables sets the "declared_tables" field.
func (_c *PluginCreate) SetDeclaredTables(v []string) *PluginCreate {
	_c.mutation.SetDeclaredTables(v)
	return _c
}

// SetMetaSnapshot sets the "meta_snapshot" field.
func (_c *PluginCreate) SetMetaSnapshot(v map[string]interface{}) *PluginCreate {
	_c.mutation.SetMetaSnapshot(v)
	return _c
}

// SetID sets the "id" field.
func (_c *PluginCreate) SetID(v string) *PluginCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the PluginMutation object of the builder.
func (_c *PluginCreate) Mutation() *PluginMutation {
	return _c.mutation
}

// Save creates the Plugin in the database.
func (_c *PluginCreate) Save(ctx context.Context) (*Plugin, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PluginCreate) SaveX(ctx context.Context) *Plugin {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PluginCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PluginCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PluginCreate) defaults() {
	if _, ok := _c.mutation.State(); !ok {
		v := plugin.DefaultState
		_c.mutation.SetState(v)
	}
	if _, ok := _c.mutation.InstalledAt(); !ok {
		v := plugin.DefaultInstalledAt()
		_c.mutation.SetInstalledAt(v)
	}
	if _, ok := _c.mutation.DeclaredTables(); !ok {
		v := plugin.DefaultDeclaredTables
		_c.mutation.SetDeclaredTables(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PluginCreate) check() error {
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "Plugin.version"`)}
	}
	if v, ok := _c.mutation.Version(); ok {
		if err := plugin.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "Plugin.version": %w`, err)}
		}
	}
	if _, ok := _c.mutation.APIVersion(); !ok {
		return &ValidationError{Name: "api_version", err: errors.New(`ent: missing required field "Plugin.api_version"`)}
	}
	if v, ok := _c.mutation.APIVersion(); ok {
		if err := plugin.APIVersionValidator(v); err != nil {
			return &ValidationError{Name: "api_version", err: fmt.Errorf(`ent: validator failed for field "Plugin.api_version": %w`, err)}
		}
	}
	if _, ok := _c.mutation.State(); !ok {
		return &ValidationError{Name: "state", err: errors.New(`ent: missing required field "Plugin.state"`)}
	}
	if v, ok := _c.mutation.State(); ok {
		if err := plugin.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "Plugin.state": %w`, err)}
		}
	}
	if _, ok := _c.mutation.InstalledAt(); !ok {
		return &ValidationError{Name: "installed_at", err: errors.New(`ent: missing required field "Plugin.installed_at"`)}
	}
	if _, ok := _c.mutation.DeclaredTables(); !ok {
		return &ValidationError{Name: "declared_tables", err: errors.New(`ent: missing required field "Plugin.declared_tables"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := plugin.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "Plugin.id": %w`, err)}
		}
	}
	return nil
}

func (_c *PluginCreate) sqlSave(ctx context.Context) (*Plugin, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Plugin.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PluginCreate) createSpec() (*Plugin, *sqlgraph.CreateSpec) {
	var (
		_node = &Plugin{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(plugin.Table, sqlgraph.NewFieldSpec(plugin.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(plugin.FieldVersion, field.TypeString, value)
		_node.Version = value
	}
	if value, ok := _c.mutation.APIVersion(); ok {
		_spec.SetField(plugin.FieldAPIVersion, field.TypeString, value)
		_node.APIVersion = value
	}
	if value, ok := _c.mutation.State(); ok {
		_spec.SetField(plugin.FieldState, field.TypeEnum, value)
		_node.State = value
	}
	if value, ok := _c.mutation.InstalledAt(); ok {
		_spec.SetField(plugin.FieldInstalledAt, field.TypeTime, value)
		_node.InstalledAt = value
	}
	if value, ok := _c.mutation.LastEnabledAt(); ok {
		_spec.SetField(plugin.FieldLastEnabledAt, field.TypeTime, value)
		_node.LastEnabledAt = &value
	}
	if value, ok := _c.mutation.DeclaredTables(); ok {
		_spec.SetField(plugin.FieldDeclaredTables, field.TypeJSON, value)
		_node.DeclaredTables = value
	}
	if value, ok := _c.mutation.MetaSnapshot(); ok {
		_spec.SetField(plugin.FieldMetaSnapshot, field.TypeJSON, value)
		_node.MetaSnapshot = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Plugin.Create().
//		SetVersion(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PluginUpsert) {
//			SetVersion(v+v).
//		}).
//		Exec(ctx)
func (_c *PluginCreate) OnConflict(opts ...sql.ConflictOption) *PluginUpsertOne {
	_c.conflict = opts
	return &PluginUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Plugin.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PluginCreate) OnConflictColumns(columns ...string) *PluginUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PluginUpsertOne{
		create: _c,
	}
}

type (
	// PluginUpsertOne is the builder for "upsert"-ing
	//  one Plugin node.
	PluginUpsertOne struct {
		create *PluginCreate
	}

	// PluginUpsert is the "OnConflict" setter.
	PluginUpsert struct {
		*sql.UpdateSet
	}
)

// SetVersion sets the "version" field.
func (u *PluginUpsert) SetVersion(v string) *PluginUpsert {
	u.Set(plugin.FieldVersion, v)
	return u
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *PluginUpsert) UpdateVersion() *PluginUpsert {
	u.SetExcluded(plugin.FieldVersion)
	return u
}

// SetAPIVersion sets the "api_version" field.
func (u *PluginUpsert) SetAPIVersion(v string) *PluginUpsert {
	u.Set(plugin.FieldAPIVersion, v)
	return u
}

// UpdateAPIVersion sets the "api_version" field to the value that was provided on create.
func (u *PluginUpsert) UpdateAPIVersion() *PluginUpsert {
	u.SetExcluded(plugin.FieldAPIVersion)
	return u
}

// SetState sets the "state" field.
func (u *PluginUpsert) SetState(v plugin.State) *PluginUpsert {
	u.Set(plugin.FieldState, v)
	return u
}

// UpdateState sets the "state" field to the value that was provided on create.
func (u *PluginUpsert) UpdateState() *PluginUpsert {
	u.SetExcluded(plugin.FieldState)
	return u
}

// SetLastEnabledAt sets the "last_enabled_at" field.
func (u *PluginUpsert) SetLastEnabledAt(v time.Time) *PluginUpsert {
	u.Set(plugin.FieldLastEnabledAt, v)
	return u
}

// UpdateLastEnabledAt sets the "last_enabled_at" field to the value that was provided on create.
func (u *PluginUpsert) UpdateLastEnabledAt() *PluginUpsert {
	u.SetExcluded(plugin.FieldLastEnabledAt)
	return u
}

// ClearLastEnabledAt clears the value of the "last_enabled_at" field.
func (u *PluginUpsert) ClearLastEnabledAt() *PluginUpsert {
	u.SetNull(plugin.FieldLastEnabledAt)
	return u
}

// SetDeclaredTables sets the "declared_tables" field.
func (u *PluginUpsert) SetDeclaredTables(v []string) *PluginUpsert {
	u.Set(plugin.FieldDeclaredTables, v)
	return u
}

// UpdateDeclaredTables sets the "declared_tables" field to the value that was provided on create.
func (u *PluginUpsert) UpdateDeclaredTables() *PluginUpsert {
	u.SetExcluded(plugin.FieldDeclaredTables)
	return u
}

// SetMetaSnapshot sets the "meta_snapshot" field.
func (u *PluginUpsert) SetMetaSnapshot(v map[string]interface{}) *PluginUpsert {
	u.Set(plugin.FieldMetaSnapshot, v)
	return u
}

// UpdateMetaSnapshot sets the "meta_snapshot" field to the value that was provided on create.
func (u *PluginUpsert) UpdateMetaSnapshot() *PluginUpsert {
	u.SetExcluded(plugin.FieldMetaSnapshot)
	return u
}

// ClearMetaSnapshot clears the value of the "meta_snapshot" field.
func (u *PluginUpsert) ClearMetaSnapshot() *PluginUpsert {
	u.SetNull(plugin.FieldMetaSnapshot)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Plugin.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(plugin.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *PluginUpsertOne) UpdateNewValues() *PluginUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(plugin.FieldID)
		}
		if _, exists := u.create.mutation.InstalledAt(); exists {
			s.SetIgnore(plugin.FieldInstalledAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Plugin.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *PluginUpsertOne) Ignore() *PluginUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PluginUpsertOne) DoNothing() *PluginUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PluginCreate.OnConflict
// documentation for more info.
func (u *PluginUpsertOne) Update(set func(*PluginUpsert)) *PluginUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PluginUpsert{UpdateSet: update})
	}))
	return u
}

// SetVersion sets the "version" field.
func (u *PluginUpsertOne) SetVersion(v string) *PluginUpsertOne {
	return u.Update(func(s *PluginUpsert) {
		s.SetVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *PluginUpsertOne) UpdateVersion() *PluginUpsertOne {
	return u.Update(func(s *PluginUpsert) {
		s.UpdateVersion()
	})
}

// SetAPIVersion sets the "api_version" field.
func (u *PluginUpsertOne) SetAPIVersion(v string) *PluginUpsertOne {
	return u.Update(func(s *PluginUpsert) {
		s.SetAPIVersion(v)
	})
}

// UpdateAPIVersion sets the "api_version" field to the value that was provided on create.
func (u *PluginUpsertOne) UpdateAPIVersion() *PluginUpsertOne {
	return u.Update(func(s *PluginUpsert) {
		s.UpdateAPIVersion()
	})
}

// SetState sets the "state" field.
func (u *PluginUpsertOne) SetState(v plugin.State) *PluginUpsertOne {
	return u.Update(func(s *PluginUpsert) {
		s.SetState(v)
	})
}

// UpdateState sets the "state" field to the value that was provided on create.
func (u *PluginUpsertOne) UpdateState() *PluginUpsertOne {
	return u.Update(func(s *PluginUpsert) {
		s.UpdateState()
	})
}

// SetLastEnabledAt sets the "last_enabled_at" field.
func (u *PluginUpsertOne) SetLastEnabledAt(v time.Time) *PluginUpsertOne {
	return u.Update(func(s *PluginUpsert) {
		s.SetLastEnabledAt(v)
	})
}

// UpdateLastEnabledAt sets the "last_enabled_at" field to the value that was provided on create.
func (u *PluginUpsertOne) UpdateLastEnabledAt() *PluginUpsertOne {
	return u.Update(func(s *PluginUpsert) {
		s.UpdateLastEnabledAt()
	})
}

// ClearLastEnabledAt clears the value of the "last_enabled_at" field.
func (u *PluginUpsertOne) ClearLastEnabledAt() *PluginUpsertOne {
	return u.Update(func(s *PluginUpsert) {
		s.ClearLastEnabledAt()
	})
}

// SetDeclaredTables sets the "declared_tables" field.
func (u *PluginUpsertOne) SetDeclaredTables(v []string) *PluginUpsertOne {
	return u.Update(func(s *PluginUpsert) {
		s.SetDeclaredTables(v)
	})
}

// UpdateDeclaredTables sets the "declared_tables" field to the value that was provided on create.
func (u *PluginUpsertOne) UpdateDeclaredTables() *PluginUpsertOne {
	return u.Update(func(s *PluginUpsert) {
		s.UpdateDeclaredTables()
	})
}

// SetMetaSnapshot sets the "meta_snapshot" field.
func (u *PluginUpsertOne) SetMetaSnapshot(v map[string]interface{}) *PluginUpsertOne {
	return u.Update(func(s *PluginUpsert) {
		s.SetMetaSnapshot(v)
	})
}

// UpdateMetaSnapshot sets the "meta_snapshot" field to the value that was provided on create.
func (u *PluginUpsertOne) UpdateMetaSnapshot() *PluginUpsertOne {
	return u.Update(func(s *PluginUpsert) {
		s.UpdateMetaSnapshot()
	})
}

// ClearMetaSnapshot clears the value of the "meta_snapshot" field.
func (u *PluginUpsertOne) ClearMetaSnapshot() *PluginUpsertOne {
	return u.Update(func(s *PluginUpsert) {
		s.ClearMetaSnapshot()
	})
}

// Exec executes the query.
func (u *PluginUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PluginCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PluginUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *PluginUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: PluginUpsertOne.ID is not supported by MySQL driver. Use PluginUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *PluginUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// PluginCreateBulk is the builder for creating many Plugin entities in bulk.
type PluginCreateBulk struct {
	config
	err      error
	builders []*PluginCreate
	conflict []sql.ConflictOption
}

// Save creates the Plugin entities in the database.
func (_c *PluginCreateBulk) Save(ctx context.Context) ([]*Plugin, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Plugin, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PluginMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PluginCreateBulk) SaveX(ctx context.Context) []*Plugin {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PluginCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PluginCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Plugin.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PluginUpsert) {
//			SetVersion(v+v).
//		}).
//		Exec(ctx)
func (_c *PluginCreateBulk) OnConflict(opts ...sql.ConflictOption) *PluginUpsertBulk {
	_c.conflict = opts
	return &PluginUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Plugin.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PluginCreateBulk) OnConflictColumns(columns ...string) *PluginUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PluginUpsertBulk{
		create: _c,
	}
}

// PluginUpsertBulk is the builder for "upsert"-ing
// a bulk of Plugin nodes.
type PluginUpsertBulk struct {
	create *PluginCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Plugin.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(plugin.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *PluginUpsertBulk) UpdateNewValues() *PluginUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(plugin.FieldID)
			}
			if _, exists := b.mutation.InstalledAt(); exists {
				s.SetIgnore(plugin.FieldInstalledAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Plugin.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *PluginUpsertBulk) Ignore() *PluginUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PluginUpsertBulk) DoNothing() *PluginUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PluginCreateBulk.OnConflict
// documentation for more info.
func (u *PluginUpsertBulk) Update(set func(*PluginUpsert)) *PluginUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PluginUpsert{UpdateSet: update})
	}))
	return u
}

// SetVersion sets the "version" field.
func (u *PluginUpsertBulk) SetVersion(v string) *PluginUpsertBulk {
	return u.Update(func(s *PluginUpsert) {
		s.SetVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *PluginUpsertBulk) UpdateVersion() *PluginUpsertBulk {
	return u.Update(func(s *PluginUpsert) {
		s.UpdateVersion()
	})
}

// SetAPIVersion sets the "api_version" field.
func (u *PluginUpsertBulk) SetAPIVersion(v string) *PluginUpsertBulk {
	return u.Update(func(s *PluginUpsert) {
		s.SetAPIVersion(v)
	})
}

// UpdateAPIVersion sets the "api_version" field to the value that was provided on create.
func (u *PluginUpsertBulk) UpdateAPIVersion() *PluginUpsertBulk {
	return u.Update(func(s *PluginUpsert) {
		s.UpdateAPIVersion()
	})
}

// SetState sets the "state" field.
func (u *PluginUpsertBulk) SetState(v plugin.State) *PluginUpsertBulk {
	return u.Update(func(s *PluginUpsert) {
		s.SetState(v)
	})
}

// UpdateState sets the "state" field to the value that was provided on create.
func (u *PluginUpsertBulk) UpdateState() *PluginUpsertBulk {
	return u.Update(func(s *PluginUpsert) {
		s.UpdateState()
	})
}

// SetLastEnabledAt sets the "last_enabled_at" field.
func (u *PluginUpsertBulk) SetLastEnabledAt(v time.Time) *PluginUpsertBulk {
	return u.Update(func(s *PluginUpsert) {
		s.SetLastEnabledAt(v)
	})
}

// UpdateLastEnabledAt sets the "last_enabled_at" field to the value that was provided on create.
func (u *PluginUpsertBulk) UpdateLastEnabledAt() *PluginUpsertBulk {
	return u.Update(func(s *PluginUpsert) {
		s.UpdateLastEnabledAt()
	})
}

// ClearLastEnabledAt clears the value of the "last_enabled_at" field.
func (u *PluginUpsertBulk) ClearLastEnabledAt() *PluginUpsertBulk {
	return u.Update(func(s *PluginUpsert) {
		s.ClearLastEnabledAt()
	})
}

// SetDeclaredTables sets the "declared_tables" field.
func (u *PluginUpsertBulk) SetDeclaredTables(v []string) *PluginUpsertBulk {
	return u.Update(func(s *PluginUpsert) {
		s.SetDeclaredTables(v)
	})
}

// UpdateDeclaredTables sets the "declared_tables" field to the value that was provided on create.
func (u *PluginUpsertBulk) UpdateDeclaredTables() *PluginUpsertBulk {
	return u.Update(func(s *PluginUpsert) {
		s.UpdateDeclaredTables()
	})
}

// SetMetaSnapshot sets the "meta_snapshot" field.
func (u *PluginUpsertBulk) SetMetaSnapshot(v map[string]interface{}) *PluginUpsertBulk {
	return u.Update(func(s *PluginUpsert) {
		s.SetMetaSnapshot(v)
	})
}

// UpdateMetaSnapshot sets the "meta_snapshot" field to the value that was provided on create.
func (u *PluginUpsertBulk) UpdateMetaSnapshot() *PluginUpsertBulk {
	return u.Update(func(s *PluginUpsert) {
		s.UpdateMetaSnapshot()
	})
}

// ClearMetaSnapshot clears the value of the "meta_snapshot" field.
func (u *PluginUpsertBulk) ClearMetaSnapshot() *PluginUpsertBulk {
	return u.Update(func(s *PluginUpsert) {
		s.ClearMetaSnapshot()
	})
}

// Exec executes the query.
func (u *PluginUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PluginCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PluginCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PluginUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
