// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/plugin"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// PluginUpdate is the builder for updating Plugin entities.
type PluginUpdate struct {
	config
	hooks    []Hook
	mutation *PluginMutation
}

// Where appends a list predicates to the PluginUpdate builder.
func (_u *PluginUpdate) Where(ps ...predicate.Plugin) *PluginUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetVersion sets the "version" field.
func (_u *PluginUpdate) SetVersion(v string) *PluginUpdate {
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *PluginUpdate) SetNillableVersion(v *string) *PluginUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// SetAPIVersion sets the "api_version" field.
func (_u *PluginUpdate) SetAPIVersion(v string) *PluginUpdate {
	_u.mutation.SetAPIVersion(v)
	return _u
}

// SetNillableAPIVersion sets the "api_version" field if the given value is not nil.
func (_u *PluginUpdate) SetNillableAPIVersion(v *string) *PluginUpdate {
	if v != nil {
		_u.SetAPIVersion(*v)
	}
	return _u
}

// SetState sets the "state" field.
func (_u *PluginUpdate) SetState(v plugin.State) *PluginUpdate {
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *PluginUpdate) SetNillableState(v *plugin.State) *PluginUpdate {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// SetLastEnabledAt sets the "last_enabled_at" field.
func (_u *PluginUpdate) SetLastEnabledAt(v time.Time) *PluginUpdate {
	_u.mutation.SetLastEnabledAt(v)
	return _u
}

// SetNillableLastEnabledAt sets the "last_enabled_at" field if the given value is not nil.
func (_u *PluginUpdate) SetNillableLastEnabledAt(v *time.Time) *PluginUpdate {
	if v != nil {
		_u.SetLastEnabledAt(*v)
	}
	return _u
}

// ClearLastEnabledAt clears the value of the "last_enabled_at" field.
func (_u *PluginUpdate) ClearLastEnabledAt() *PluginUpdate {
	_u.mutation.ClearLastEnabledAt()
	return _u
}

// SetDeclaredTables sets the "declared_tables" field.
func (_u *PluginUpdate) SetDeclaredTables(v []string) *PluginUpdate {
	_u.mutation.SetDeclaredTables(v)
	return _u
}

// AppendDeclaredTables appends value to the "declared_tables" field.
func (_u *PluginUpdate) AppendDeclaredTables(v []string) *PluginUpdate {
	_u.mutation.AppendDeclaredTables(v)
	return _u
}

// SetMetaSnapshot sets the "meta_snapshot" field.
func (_u *PluginUpdate) SetMetaSnapshot(v map[string]interface{}) *PluginUpdate {
	_u.mutation.SetMetaSnapshot(v)
	return _u
}

// ClearMetaSnapshot clears the value of the "meta_snapshot" field.
func (_u *PluginUpdate) ClearMetaSnapshot() *PluginUpdate {
	_u.mutation.ClearMetaSnapshot()
	return _u
}

// Mutation returns the PluginMutation object of the builder.
func (_u *PluginUpdate) Mutation() *PluginMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PluginUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PluginUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PluginUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PluginUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PluginUpdate) check() error {
	if v, ok := _u.mutation.Version(); ok {
		if err := plugin.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "Plugin.version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.APIVersion(); ok {
		if err := plugin.APIVersionValidator(v); err != nil {
			return &ValidationError{Name: "api_version", err: fmt.Errorf(`ent: validator failed for field "Plugin.api_version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.State(); ok {
		if err := plugin.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "Plugin.state": %w`, err)}
		}
	}
	return nil
}

func (_u *PluginUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(plugin.Table, plugin.Columns, sqlgraph.NewFieldSpec(plugin.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(plugin.FieldVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.APIVersion(); ok {
		_spec.SetField(plugin.FieldAPIVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.State(); ok {
		_spec.SetField(plugin.FieldState, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.LastEnabledAt(); ok {
		_spec.SetField(plugin.FieldLastEnabledAt, field.TypeTime, value)
	}
	if _u.mutation.LastEnabledAtCleared() {
		_spec.ClearField(plugin.FieldLastEnabledAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeclaredTables(); ok {
		_spec.SetField(plugin.FieldDeclaredTables, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedDeclaredTables(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, plugin.FieldDeclaredTables, value)
		})
	}
	if value, ok := _u.mutation.MetaSnapshot(); ok {
		_spec.SetField(plugin.FieldMetaSnapshot, field.TypeJSON, value)
	}
	if _u.mutation.MetaSnapshotCleared() {
		_spec.ClearField(plugin.FieldMetaSnapshot, field.TypeJSON)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{plugin.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PluginUpdateOne is the builder for updating a single Plugin entity.
type PluginUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PluginMutation
}

// SetVersion sets the "version" field.
func (_u *PluginUpdateOne) SetVersion(v string) *PluginUpdateOne {
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *PluginUpdateOne) SetNillableVersion(v *string) *PluginUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// SetAPIVersion sets the "api_version" field.
func (_u *PluginUpdateOne) SetAPIVersion(v string) *PluginUpdateOne {
	_u.mutation.SetAPIVersion(v)
	return _u
}

// SetNillableAPIVersion sets the "api_version" field if the given value is not nil.
func (_u *PluginUpdateOne) SetNillableAPIVersion(v *string) *PluginUpdateOne {
	if v != nil {
		_u.SetAPIVersion(*v)
	}
	return _u
}

// SetState sets the "state" field.
func (_u *PluginUpdateOne) SetState(v plugin.State) *PluginUpdateOne {
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *PluginUpdateOne) SetNillableState(v *plugin.State) *PluginUpdateOne {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// SetLastEnabledAt sets the "last_enabled_at" field.
func (_u *PluginUpdateOne) SetLastEnabledAt(v time.Time) *PluginUpdateOne {
	_u.mutation.SetLastEnabledAt(v)
	return _u
}

// SetNillableLastEnabledAt sets the "last_enabled_at" field if the given value is not nil.
func (_u *PluginUpdateOne) SetNillableLastEnabledAt(v *time.Time) *PluginUpdateOne {
	if v != nil {
		_u.SetLastEnabledAt(*v)
	}
	return _u
}

// ClearLastEnabledAt clears the value of the "last_enabled_at" field.
func (_u *PluginUpdateOne) ClearLastEnabledAt() *PluginUpdateOne {
	_u.mutation.ClearLastEnabledAt()
	return _u
}

// SetDeclaredTables sets the "declared_tables" field.
func (_u *PluginUpdateOne) SetDeclaredTables(v []string) *PluginUpdateOne {
	_u.mutation.SetDeclaredTables(v)
	return _u
}

// AppendDeclaredTables appends value to the "declared_tables" field.
func (_u *PluginUpdateOne) AppendDeclaredTables(v []string) *PluginUpdateOne {
	_u.mutation.AppendDeclaredTables(v)
	return _u
}

// SetMetaSnapshot sets the "meta_snapshot" field.
func (_u *PluginUpdateOne) SetMetaSnapshot(v map[string]interface{}) *PluginUpdateOne {
	_u.mutation.SetMetaSnapshot(v)
	return _u
}

// ClearMetaSnapshot clears the value of the "meta_snapshot" field.
func (_u *PluginUpdateOne) ClearMetaSnapshot() *PluginUpdateOne {
	_u.mutation.ClearMetaSnapshot()
	return _u
}

// Mutation returns the PluginMutation object of the builder.
func (_u *PluginUpdateOne) Mutation() *PluginMutation {
	return _u.mutation
}

// Where appends a list predicates to the PluginUpdate builder.
func (_u *PluginUpdateOne) Where(ps ...predicate.Plugin) *PluginUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PluginUpdateOne) Select(field string, fields ...string) *PluginUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Plugin entity.
func (_u *PluginUpdateOne) Save(ctx context.Context) (*Plugin, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PluginUpdateOne) SaveX(ctx context.Context) *Plugin {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PluginUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PluginUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PluginUpdateOne) check() error {
	if v, ok := _u.mutation.Version(); ok {
		if err := plugin.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "Plugin.version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.APIVersion(); ok {
		if err := plugin.APIVersionValidator(v); err != nil {
			return &ValidationError{Name: "api_version", err: fmt.Errorf(`ent: validator failed for field "Plugin.api_version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.State(); ok {
		if err := plugin.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "Plugin.state": %w`, err)}
		}
	}
	return nil
}

func (_u *PluginUpdateOne) sqlSave(ctx context.Context) (_node *Plugin, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(plugin.Table, plugin.Columns, sqlgraph.NewFieldSpec(plugin.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Plugin.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, plugin.FieldID)
		for _, f := range fields {
			if !plugin.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != plugin.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(plugin.FieldVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.APIVersion(); ok {
		_spec.SetField(plugin.FieldAPIVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.State(); ok {
		_spec.SetField(plugin.FieldState, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.LastEnabledAt(); ok {
		_spec.SetField(plugin.FieldLastEnabledAt, field.TypeTime, value)
	}
	if _u.mutation.LastEnabledAtCleared() {
		_spec.ClearField(plugin.FieldLastEnabledAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeclaredTables(); ok {
		_spec.SetField(plugin.FieldDeclaredTables, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedDeclaredTables(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, plugin.FieldDeclaredTables, value)
		})
	}
	if value, ok := _u.mutation.MetaSnapshot(); ok {
		_spec.SetField(plugin.FieldMetaSnapshot, field.TypeJSON, value)
	}
	if _u.mutation.MetaSnapshotCleared() {
		_spec.ClearField(plugin.FieldMetaSnapshot, field.TypeJSON)
	}
	_node = &Plugin{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{plugin.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
