// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/protocol"
)

// ProtocolUpdate is the builder for updating Protocol entities.
type ProtocolUpdate struct {
	config
	hooks    []Hook
	mutation *ProtocolMutation
}

// Where appends a list predicates to the ProtocolUpdate builder.
func (_u *ProtocolUpdate) Where(ps ...predicate.Protocol) *ProtocolUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProtocolUpdate) SetUpdatedAt(v time.Time) *ProtocolUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *ProtocolUpdate) SetName(v string) *ProtocolUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ProtocolUpdate) SetNillableName(v *string) *ProtocolUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDisplayName sets the "display_name" field.
func (_u *ProtocolUpdate) SetDisplayName(v string) *ProtocolUpdate {
	_u.mutation.SetDisplayName(v)
	return _u
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_u *ProtocolUpdate) SetNillableDisplayName(v *string) *ProtocolUpdate {
	if v != nil {
		_u.SetDisplayName(*v)
	}
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *ProtocolUpdate) SetPlatform(v string) *ProtocolUpdate {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *ProtocolUpdate) SetNillablePlatform(v *string) *ProtocolUpdate {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetGatewayEndpoint sets the "gateway_endpoint" field.
func (_u *ProtocolUpdate) SetGatewayEndpoint(v string) *ProtocolUpdate {
	_u.mutation.SetGatewayEndpoint(v)
	return _u
}

// SetNillableGatewayEndpoint sets the "gateway_endpoint" field if the given value is not nil.
func (_u *ProtocolUpdate) SetNillableGatewayEndpoint(v *string) *ProtocolUpdate {
	if v != nil {
		_u.SetGatewayEndpoint(*v)
	}
	return _u
}

// SetIconSvg sets the "icon_svg" field.
func (_u *ProtocolUpdate) SetIconSvg(v string) *ProtocolUpdate {
	_u.mutation.SetIconSvg(v)
	return _u
}

// SetNillableIconSvg sets the "icon_svg" field if the given value is not nil.
func (_u *ProtocolUpdate) SetNillableIconSvg(v *string) *ProtocolUpdate {
	if v != nil {
		_u.SetIconSvg(*v)
	}
	return _u
}

// ClearIconSvg clears the value of the "icon_svg" field.
func (_u *ProtocolUpdate) ClearIconSvg() *ProtocolUpdate {
	_u.mutation.ClearIconSvg()
	return _u
}

// SetThemeColor sets the "theme_color" field.
func (_u *ProtocolUpdate) SetThemeColor(v string) *ProtocolUpdate {
	_u.mutation.SetThemeColor(v)
	return _u
}

// SetNillableThemeColor sets the "theme_color" field if the given value is not nil.
func (_u *ProtocolUpdate) SetNillableThemeColor(v *string) *ProtocolUpdate {
	if v != nil {
		_u.SetThemeColor(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *ProtocolUpdate) SetSortOrder(v int) *ProtocolUpdate {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *ProtocolUpdate) SetNillableSortOrder(v *int) *ProtocolUpdate {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *ProtocolUpdate) AddSortOrder(v int) *ProtocolUpdate {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *ProtocolUpdate) SetStatus(v string) *ProtocolUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ProtocolUpdate) SetNillableStatus(v *string) *ProtocolUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddGroupIDs adds the "groups" edge to the Group entity by IDs.
func (_u *ProtocolUpdate) AddGroupIDs(ids ...int64) *ProtocolUpdate {
	_u.mutation.AddGroupIDs(ids...)
	return _u
}

// AddGroups adds the "groups" edges to the Group entity.
func (_u *ProtocolUpdate) AddGroups(v ...*Group) *ProtocolUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddGroupIDs(ids...)
}

// Mutation returns the ProtocolMutation object of the builder.
func (_u *ProtocolUpdate) Mutation() *ProtocolMutation {
	return _u.mutation
}

// ClearGroups clears all "groups" edges to the Group entity.
func (_u *ProtocolUpdate) ClearGroups() *ProtocolUpdate {
	_u.mutation.ClearGroups()
	return _u
}

// RemoveGroupIDs removes the "groups" edge to Group entities by IDs.
func (_u *ProtocolUpdate) RemoveGroupIDs(ids ...int64) *ProtocolUpdate {
	_u.mutation.RemoveGroupIDs(ids...)
	return _u
}

// RemoveGroups removes "groups" edges to Group entities.
func (_u *ProtocolUpdate) RemoveGroups(v ...*Group) *ProtocolUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveGroupIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ProtocolUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProtocolUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ProtocolUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProtocolUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProtocolUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := protocol.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProtocolUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := protocol.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Protocol.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DisplayName(); ok {
		if err := protocol.DisplayNameValidator(v); err != nil {
			return &ValidationError{Name: "display_name", err: fmt.Errorf(`ent: validator failed for field "Protocol.display_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Platform(); ok {
		if err := protocol.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "Protocol.platform": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GatewayEndpoint(); ok {
		if err := protocol.GatewayEndpointValidator(v); err != nil {
			return &ValidationError{Name: "gateway_endpoint", err: fmt.Errorf(`ent: validator failed for field "Protocol.gateway_endpoint": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ThemeColor(); ok {
		if err := protocol.ThemeColorValidator(v); err != nil {
			return &ValidationError{Name: "theme_color", err: fmt.Errorf(`ent: validator failed for field "Protocol.theme_color": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := protocol.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Protocol.status": %w`, err)}
		}
	}
	return nil
}

func (_u *ProtocolUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(protocol.Table, protocol.Columns, sqlgraph.NewFieldSpec(protocol.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(protocol.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(protocol.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayName(); ok {
		_spec.SetField(protocol.FieldDisplayName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(protocol.FieldPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.GatewayEndpoint(); ok {
		_spec.SetField(protocol.FieldGatewayEndpoint, field.TypeString, value)
	}
	if value, ok := _u.mutation.IconSvg(); ok {
		_spec.SetField(protocol.FieldIconSvg, field.TypeString, value)
	}
	if _u.mutation.IconSvgCleared() {
		_spec.ClearField(protocol.FieldIconSvg, field.TypeString)
	}
	if value, ok := _u.mutation.ThemeColor(); ok {
		_spec.SetField(protocol.FieldThemeColor, field.TypeString, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(protocol.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(protocol.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(protocol.FieldStatus, field.TypeString, value)
	}
	if _u.mutation.GroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   protocol.GroupsTable,
			Columns: []string{protocol.GroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedGroupsIDs(); len(nodes) > 0 && !_u.mutation.GroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   protocol.GroupsTable,
			Columns: []string{protocol.GroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   protocol.GroupsTable,
			Columns: []string{protocol.GroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{protocol.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ProtocolUpdateOne is the builder for updating a single Protocol entity.
type ProtocolUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProtocolMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProtocolUpdateOne) SetUpdatedAt(v time.Time) *ProtocolUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *ProtocolUpdateOne) SetName(v string) *ProtocolUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ProtocolUpdateOne) SetNillableName(v *string) *ProtocolUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDisplayName sets the "display_name" field.
func (_u *ProtocolUpdateOne) SetDisplayName(v string) *ProtocolUpdateOne {
	_u.mutation.SetDisplayName(v)
	return _u
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_u *ProtocolUpdateOne) SetNillableDisplayName(v *string) *ProtocolUpdateOne {
	if v != nil {
		_u.SetDisplayName(*v)
	}
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *ProtocolUpdateOne) SetPlatform(v string) *ProtocolUpdateOne {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *ProtocolUpdateOne) SetNillablePlatform(v *string) *ProtocolUpdateOne {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetGatewayEndpoint sets the "gateway_endpoint" field.
func (_u *ProtocolUpdateOne) SetGatewayEndpoint(v string) *ProtocolUpdateOne {
	_u.mutation.SetGatewayEndpoint(v)
	return _u
}

// SetNillableGatewayEndpoint sets the "gateway_endpoint" field if the given value is not nil.
func (_u *ProtocolUpdateOne) SetNillableGatewayEndpoint(v *string) *ProtocolUpdateOne {
	if v != nil {
		_u.SetGatewayEndpoint(*v)
	}
	return _u
}

// SetIconSvg sets the "icon_svg" field.
func (_u *ProtocolUpdateOne) SetIconSvg(v string) *ProtocolUpdateOne {
	_u.mutation.SetIconSvg(v)
	return _u
}

// SetNillableIconSvg sets the "icon_svg" field if the given value is not nil.
func (_u *ProtocolUpdateOne) SetNillableIconSvg(v *string) *ProtocolUpdateOne {
	if v != nil {
		_u.SetIconSvg(*v)
	}
	return _u
}

// ClearIconSvg clears the value of the "icon_svg" field.
func (_u *ProtocolUpdateOne) ClearIconSvg() *ProtocolUpdateOne {
	_u.mutation.ClearIconSvg()
	return _u
}

// SetThemeColor sets the "theme_color" field.
func (_u *ProtocolUpdateOne) SetThemeColor(v string) *ProtocolUpdateOne {
	_u.mutation.SetThemeColor(v)
	return _u
}

// SetNillableThemeColor sets the "theme_color" field if the given value is not nil.
func (_u *ProtocolUpdateOne) SetNillableThemeColor(v *string) *ProtocolUpdateOne {
	if v != nil {
		_u.SetThemeColor(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *ProtocolUpdateOne) SetSortOrder(v int) *ProtocolUpdateOne {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *ProtocolUpdateOne) SetNillableSortOrder(v *int) *ProtocolUpdateOne {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *ProtocolUpdateOne) AddSortOrder(v int) *ProtocolUpdateOne {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *ProtocolUpdateOne) SetStatus(v string) *ProtocolUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ProtocolUpdateOne) SetNillableStatus(v *string) *ProtocolUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddGroupIDs adds the "groups" edge to the Group entity by IDs.
func (_u *ProtocolUpdateOne) AddGroupIDs(ids ...int64) *ProtocolUpdateOne {
	_u.mutation.AddGroupIDs(ids...)
	return _u
}

// AddGroups adds the "groups" edges to the Group entity.
func (_u *ProtocolUpdateOne) AddGroups(v ...*Group) *ProtocolUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddGroupIDs(ids...)
}

// Mutation returns the ProtocolMutation object of the builder.
func (_u *ProtocolUpdateOne) Mutation() *ProtocolMutation {
	return _u.mutation
}

// ClearGroups clears all "groups" edges to the Group entity.
func (_u *ProtocolUpdateOne) ClearGroups() *ProtocolUpdateOne {
	_u.mutation.ClearGroups()
	return _u
}

// RemoveGroupIDs removes the "groups" edge to Group entities by IDs.
func (_u *ProtocolUpdateOne) RemoveGroupIDs(ids ...int64) *ProtocolUpdateOne {
	_u.mutation.RemoveGroupIDs(ids...)
	return _u
}

// RemoveGroups removes "groups" edges to Group entities.
func (_u *ProtocolUpdateOne) RemoveGroups(v ...*Group) *ProtocolUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveGroupIDs(ids...)
}

// Where appends a list predicates to the ProtocolUpdate builder.
func (_u *ProtocolUpdateOne) Where(ps ...predicate.Protocol) *ProtocolUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ProtocolUpdateOne) Select(field string, fields ...string) *ProtocolUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Protocol entity.
func (_u *ProtocolUpdateOne) Save(ctx context.Context) (*Protocol, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProtocolUpdateOne) SaveX(ctx context.Context) *Protocol {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ProtocolUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProtocolUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProtocolUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := protocol.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProtocolUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := protocol.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Protocol.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DisplayName(); ok {
		if err := protocol.DisplayNameValidator(v); err != nil {
			return &ValidationError{Name: "display_name", err: fmt.Errorf(`ent: validator failed for field "Protocol.display_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Platform(); ok {
		if err := protocol.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "Protocol.platform": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GatewayEndpoint(); ok {
		if err := protocol.GatewayEndpointValidator(v); err != nil {
			return &ValidationError{Name: "gateway_endpoint", err: fmt.Errorf(`ent: validator failed for field "Protocol.gateway_endpoint": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ThemeColor(); ok {
		if err := protocol.ThemeColorValidator(v); err != nil {
			return &ValidationError{Name: "theme_color", err: fmt.Errorf(`ent: validator failed for field "Protocol.theme_color": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := protocol.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Protocol.status": %w`, err)}
		}
	}
	return nil
}

func (_u *ProtocolUpdateOne) sqlSave(ctx context.Context) (_node *Protocol, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(protocol.Table, protocol.Columns, sqlgraph.NewFieldSpec(protocol.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Protocol.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, protocol.FieldID)
		for _, f := range fields {
			if !protocol.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != protocol.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(protocol.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(protocol.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayName(); ok {
		_spec.SetField(protocol.FieldDisplayName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(protocol.FieldPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.GatewayEndpoint(); ok {
		_spec.SetField(protocol.FieldGatewayEndpoint, field.TypeString, value)
	}
	if value, ok := _u.mutation.IconSvg(); ok {
		_spec.SetField(protocol.FieldIconSvg, field.TypeString, value)
	}
	if _u.mutation.IconSvgCleared() {
		_spec.ClearField(protocol.FieldIconSvg, field.TypeString)
	}
	if value, ok := _u.mutation.ThemeColor(); ok {
		_spec.SetField(protocol.FieldThemeColor, field.TypeString, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(protocol.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(protocol.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(protocol.FieldStatus, field.TypeString, value)
	}
	if _u.mutation.GroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   protocol.GroupsTable,
			Columns: []string{protocol.GroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedGroupsIDs(); len(nodes) > 0 && !_u.mutation.GroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   protocol.GroupsTable,
			Columns: []string{protocol.GroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   protocol.GroupsTable,
			Columns: []string{protocol.GroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Protocol{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{protocol.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
