// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/protocol"
)

// Protocol is the model entity for the Protocol schema.
type Protocol struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// DisplayName holds the value of the "display_name" field.
	DisplayName string `json:"display_name,omitempty"`
	// Platform holds the value of the "platform" field.
	Platform string `json:"platform,omitempty"`
	// GatewayEndpoint holds the value of the "gateway_endpoint" field.
	GatewayEndpoint string `json:"gateway_endpoint,omitempty"`
	// IconSvg holds the value of the "icon_svg" field.
	IconSvg *string `json:"icon_svg,omitempty"`
	// ThemeColor holds the value of the "theme_color" field.
	ThemeColor string `json:"theme_color,omitempty"`
	// SortOrder holds the value of the "sort_order" field.
	SortOrder int `json:"sort_order,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ProtocolQuery when eager-loading is set.
	Edges        ProtocolEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ProtocolEdges holds the relations/edges for other nodes in the graph.
type ProtocolEdges struct {
	// Groups holds the value of the groups edge.
	Groups []*Group `json:"groups,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// GroupsOrErr returns the Groups value or an error if the edge
// was not loaded in eager-loading.
func (e ProtocolEdges) GroupsOrErr() ([]*Group, error) {
	if e.loadedTypes[0] {
		return e.Groups, nil
	}
	return nil, &NotLoadedError{edge: "groups"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Protocol) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case protocol.FieldID, protocol.FieldSortOrder:
			values[i] = new(sql.NullInt64)
		case protocol.FieldName, protocol.FieldDisplayName, protocol.FieldPlatform, protocol.FieldGatewayEndpoint, protocol.FieldIconSvg, protocol.FieldThemeColor, protocol.FieldStatus:
			values[i] = new(sql.NullString)
		case protocol.FieldCreatedAt, protocol.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Protocol fields.
func (_m *Protocol) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case protocol.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case protocol.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case protocol.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case protocol.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case protocol.FieldDisplayName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field display_name", values[i])
			} else if value.Valid {
				_m.DisplayName = value.String
			}
		case protocol.FieldPlatform:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field platform", values[i])
			} else if value.Valid {
				_m.Platform = value.String
			}
		case protocol.FieldGatewayEndpoint:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field gateway_endpoint", values[i])
			} else if value.Valid {
				_m.GatewayEndpoint = value.String
			}
		case protocol.FieldIconSvg:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field icon_svg", values[i])
			} else if value.Valid {
				_m.IconSvg = new(string)
				*_m.IconSvg = value.String
			}
		case protocol.FieldThemeColor:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field theme_color", values[i])
			} else if value.Valid {
				_m.ThemeColor = value.String
			}
		case protocol.FieldSortOrder:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sort_order", values[i])
			} else if value.Valid {
				_m.SortOrder = int(value.Int64)
			}
		case protocol.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Protocol.
// This includes values selected through modifiers, order, etc.
func (_m *Protocol) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryGroups queries the "groups" edge of the Protocol entity.
func (_m *Protocol) QueryGroups() *GroupQuery {
	return NewProtocolClient(_m.config).QueryGroups(_m)
}

// Update returns a builder for updating this Protocol.
// Note that you need to call Protocol.Unwrap() before calling this method if this Protocol
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Protocol) Update() *ProtocolUpdateOne {
	return NewProtocolClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Protocol entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Protocol) Unwrap() *Protocol {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Protocol is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Protocol) String() string {
	var builder strings.Builder
	builder.WriteString("Protocol(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("display_name=")
	builder.WriteString(_m.DisplayName)
	builder.WriteString(", ")
	builder.WriteString("platform=")
	builder.WriteString(_m.Platform)
	builder.WriteString(", ")
	builder.WriteString("gateway_endpoint=")
	builder.WriteString(_m.GatewayEndpoint)
	builder.WriteString(", ")
	if v := _m.IconSvg; v != nil {
		builder.WriteString("icon_svg=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("theme_color=")
	builder.WriteString(_m.ThemeColor)
	builder.WriteString(", ")
	builder.WriteString("sort_order=")
	builder.WriteString(fmt.Sprintf("%v", _m.SortOrder))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteByte(')')
	return builder.String()
}

// Protocols is a parsable slice of Protocol.
type Protocols []*Protocol
