// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/protocol"
)

// ProtocolCreate is the builder for creating a Protocol entity.
type ProtocolCreate struct {
	config
	mutation *ProtocolMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *ProtocolCreate) SetCreatedAt(v time.Time) *ProtocolCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ProtocolCreate) SetNillableCreatedAt(v *time.Time) *ProtocolCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ProtocolCreate) SetUpdatedAt(v time.Time) *ProtocolCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ProtocolCreate) SetNillableUpdatedAt(v *time.Time) *ProtocolCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *ProtocolCreate) SetName(v string) *ProtocolCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDisplayName sets the "display_name" field.
func (_c *ProtocolCreate) SetDisplayName(v string) *ProtocolCreate {
	_c.mutation.SetDisplayName(v)
	return _c
}

// SetPlatform sets the "platform" field.
func (_c *ProtocolCreate) SetPlatform(v string) *ProtocolCreate {
	_c.mutation.SetPlatform(v)
	return _c
}

// SetGatewayEndpoint sets the "gateway_endpoint" field.
func (_c *ProtocolCreate) SetGatewayEndpoint(v string) *ProtocolCreate {
	_c.mutation.SetGatewayEndpoint(v)
	return _c
}

// SetIconSvg sets the "icon_svg" field.
func (_c *ProtocolCreate) SetIconSvg(v string) *ProtocolCreate {
	_c.mutation.SetIconSvg(v)
	return _c
}

// SetNillableIconSvg sets the "icon_svg" field if the given value is not nil.
func (_c *ProtocolCreate) SetNillableIconSvg(v *string) *ProtocolCreate {
	if v != nil {
		_c.SetIconSvg(*v)
	}
	return _c
}

// SetThemeColor sets the "theme_color" field.
func (_c *ProtocolCreate) SetThemeColor(v string) *ProtocolCreate {
	_c.mutation.SetThemeColor(v)
	return _c
}

// SetNillableThemeColor sets the "theme_color" field if the given value is not nil.
func (_c *ProtocolCreate) SetNillableThemeColor(v *string) *ProtocolCreate {
	if v != nil {
		_c.SetThemeColor(*v)
	}
	return _c
}

// SetSortOrder sets the "sort_order" field.
func (_c *ProtocolCreate) SetSortOrder(v int) *ProtocolCreate {
	_c.mutation.SetSortOrder(v)
	return _c
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_c *ProtocolCreate) SetNillableSortOrder(v *int) *ProtocolCreate {
	if v != nil {
		_c.SetSortOrder(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *ProtocolCreate) SetStatus(v string) *ProtocolCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ProtocolCreate) SetNillableStatus(v *string) *ProtocolCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// AddGroupIDs adds the "groups" edge to the Group entity by IDs.
func (_c *ProtocolCreate) AddGroupIDs(ids ...int64) *ProtocolCreate {
	_c.mutation.AddGroupIDs(ids...)
	return _c
}

// AddGroups adds the "groups" edges to the Group entity.
func (_c *ProtocolCreate) AddGroups(v ...*Group) *ProtocolCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddGroupIDs(ids...)
}

// Mutation returns the ProtocolMutation object of the builder.
func (_c *ProtocolCreate) Mutation() *ProtocolMutation {
	return _c.mutation
}

// Save creates the Protocol in the database.
func (_c *ProtocolCreate) Save(ctx context.Context) (*Protocol, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ProtocolCreate) SaveX(ctx context.Context) *Protocol {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProtocolCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProtocolCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ProtocolCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := protocol.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := protocol.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ThemeColor(); !ok {
		v := protocol.DefaultThemeColor
		_c.mutation.SetThemeColor(v)
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		v := protocol.DefaultSortOrder
		_c.mutation.SetSortOrder(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := protocol.DefaultStatus
		_c.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ProtocolCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Protocol.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Protocol.updated_at"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Protocol.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := protocol.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Protocol.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DisplayName(); !ok {
		return &ValidationError{Name: "display_name", err: errors.New(`ent: missing required field "Protocol.display_name"`)}
	}
	if v, ok := _c.mutation.DisplayName(); ok {
		if err := protocol.DisplayNameValidator(v); err != nil {
			return &ValidationError{Name: "display_name", err: fmt.Errorf(`ent: validator failed for field "Protocol.display_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Platform(); !ok {
		return &ValidationError{Name: "platform", err: errors.New(`ent: missing required field "Protocol.platform"`)}
	}
	if v, ok := _c.mutation.Platform(); ok {
		if err := protocol.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "Protocol.platform": %w`, err)}
		}
	}
	if _, ok := _c.mutation.GatewayEndpoint(); !ok {
		return &ValidationError{Name: "gateway_endpoint", err: errors.New(`ent: missing required field "Protocol.gateway_endpoint"`)}
	}
	if v, ok := _c.mutation.GatewayEndpoint(); ok {
		if err := protocol.GatewayEndpointValidator(v); err != nil {
			return &ValidationError{Name: "gateway_endpoint", err: fmt.Errorf(`ent: validator failed for field "Protocol.gateway_endpoint": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ThemeColor(); !ok {
		return &ValidationError{Name: "theme_color", err: errors.New(`ent: missing required field "Protocol.theme_color"`)}
	}
	if v, ok := _c.mutation.ThemeColor(); ok {
		if err := protocol.ThemeColorValidator(v); err != nil {
			return &ValidationError{Name: "theme_color", err: fmt.Errorf(`ent: validator failed for field "Protocol.theme_color": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		return &ValidationError{Name: "sort_order", err: errors.New(`ent: missing required field "Protocol.sort_order"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Protocol.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := protocol.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Protocol.status": %w`, err)}
		}
	}
	return nil
}

func (_c *ProtocolCreate) sqlSave(ctx context.Context) (*Protocol, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ProtocolCreate) createSpec() (*Protocol, *sqlgraph.CreateSpec) {
	var (
		_node = &Protocol{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(protocol.Table, sqlgraph.NewFieldSpec(protocol.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(protocol.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(protocol.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(protocol.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.DisplayName(); ok {
		_spec.SetField(protocol.FieldDisplayName, field.TypeString, value)
		_node.DisplayName = value
	}
	if value, ok := _c.mutation.Platform(); ok {
		_spec.SetField(protocol.FieldPlatform, field.TypeString, value)
		_node.Platform = value
	}
	if value, ok := _c.mutation.GatewayEndpoint(); ok {
		_spec.SetField(protocol.FieldGatewayEndpoint, field.TypeString, value)
		_node.GatewayEndpoint = value
	}
	if value, ok := _c.mutation.IconSvg(); ok {
		_spec.SetField(protocol.FieldIconSvg, field.TypeString, value)
		_node.IconSvg = &value
	}
	if value, ok := _c.mutation.ThemeColor(); ok {
		_spec.SetField(protocol.FieldThemeColor, field.TypeString, value)
		_node.ThemeColor = value
	}
	if value, ok := _c.mutation.SortOrder(); ok {
		_spec.SetField(protocol.FieldSortOrder, field.TypeInt, value)
		_node.SortOrder = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(protocol.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if nodes := _c.mutation.GroupsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   protocol.GroupsTable,
			Columns: []string{protocol.GroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Protocol.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ProtocolUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ProtocolCreate) OnConflict(opts ...sql.ConflictOption) *ProtocolUpsertOne {
	_c.conflict = opts
	return &ProtocolUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Protocol.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ProtocolCreate) OnConflictColumns(columns ...string) *ProtocolUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ProtocolUpsertOne{
		create: _c,
	}
}

type (
	// ProtocolUpsertOne is the builder for "upsert"-ing
	//  one Protocol node.
	ProtocolUpsertOne struct {
		create *ProtocolCreate
	}

	// ProtocolUpsert is the "OnConflict" setter.
	ProtocolUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *ProtocolUpsert) SetUpdatedAt(v time.Time) *ProtocolUpsert {
	u.Set(protocol.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ProtocolUpsert) UpdateUpdatedAt() *ProtocolUpsert {
	u.SetExcluded(protocol.FieldUpdatedAt)
	return u
}

// SetName sets the "name" field.
func (u *ProtocolUpsert) SetName(v string) *ProtocolUpsert {
	u.Set(protocol.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ProtocolUpsert) UpdateName() *ProtocolUpsert {
	u.SetExcluded(protocol.FieldName)
	return u
}

// SetDisplayName sets the "display_name" field.
func (u *ProtocolUpsert) SetDisplayName(v string) *ProtocolUpsert {
	u.Set(protocol.FieldDisplayName, v)
	return u
}

// UpdateDisplayName sets the "display_name" field to the value that was provided on create.
func (u *ProtocolUpsert) UpdateDisplayName() *ProtocolUpsert {
	u.SetExcluded(protocol.FieldDisplayName)
	return u
}

// SetPlatform sets the "platform" field.
func (u *ProtocolUpsert) SetPlatform(v string) *ProtocolUpsert {
	u.Set(protocol.FieldPlatform, v)
	return u
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *ProtocolUpsert) UpdatePlatform() *ProtocolUpsert {
	u.SetExcluded(protocol.FieldPlatform)
	return u
}

// SetGatewayEndpoint sets the "gateway_endpoint" field.
func (u *ProtocolUpsert) SetGatewayEndpoint(v string) *ProtocolUpsert {
	u.Set(protocol.FieldGatewayEndpoint, v)
	return u
}

// UpdateGatewayEndpoint sets the "gateway_endpoint" field to the value that was provided on create.
func (u *ProtocolUpsert) UpdateGatewayEndpoint() *ProtocolUpsert {
	u.SetExcluded(protocol.FieldGatewayEndpoint)
	return u
}

// SetIconSvg sets the "icon_svg" field.
func (u *ProtocolUpsert) SetIconSvg(v string) *ProtocolUpsert {
	u.Set(protocol.FieldIconSvg, v)
	return u
}

// UpdateIconSvg sets the "icon_svg" field to the value that was provided on create.
func (u *ProtocolUpsert) UpdateIconSvg() *ProtocolUpsert {
	u.SetExcluded(protocol.FieldIconSvg)
	return u
}

// ClearIconSvg clears the value of the "icon_svg" field.
func (u *ProtocolUpsert) ClearIconSvg() *ProtocolUpsert {
	u.SetNull(protocol.FieldIconSvg)
	return u
}

// SetThemeColor sets the "theme_color" field.
func (u *ProtocolUpsert) SetThemeColor(v string) *ProtocolUpsert {
	u.Set(protocol.FieldThemeColor, v)
	return u
}

// UpdateThemeColor sets the "theme_color" field to the value that was provided on create.
func (u *ProtocolUpsert) UpdateThemeColor() *ProtocolUpsert {
	u.SetExcluded(protocol.FieldThemeColor)
	return u
}

// SetSortOrder sets the "sort_order" field.
func (u *ProtocolUpsert) SetSortOrder(v int) *ProtocolUpsert {
	u.Set(protocol.FieldSortOrder, v)
	return u
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *ProtocolUpsert) UpdateSortOrder() *ProtocolUpsert {
	u.SetExcluded(protocol.FieldSortOrder)
	return u
}

// AddSortOrder adds v to the "sort_order" field.
func (u *ProtocolUpsert) AddSortOrder(v int) *ProtocolUpsert {
	u.Add(protocol.FieldSortOrder, v)
	return u
}

// SetStatus sets the "status" field.
func (u *ProtocolUpsert) SetStatus(v string) *ProtocolUpsert {
	u.Set(protocol.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ProtocolUpsert) UpdateStatus() *ProtocolUpsert {
	u.SetExcluded(protocol.FieldStatus)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Protocol.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ProtocolUpsertOne) UpdateNewValues() *ProtocolUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(protocol.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Protocol.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ProtocolUpsertOne) Ignore() *ProtocolUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ProtocolUpsertOne) DoNothing() *ProtocolUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ProtocolCreate.OnConflict
// documentation for more info.
func (u *ProtocolUpsertOne) Update(set func(*ProtocolUpsert)) *ProtocolUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ProtocolUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ProtocolUpsertOne) SetUpdatedAt(v time.Time) *ProtocolUpsertOne {
	return u.Update(func(s *ProtocolUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ProtocolUpsertOne) UpdateUpdatedAt() *ProtocolUpsertOne {
	return u.Update(func(s *ProtocolUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetName sets the "name" field.
func (u *ProtocolUpsertOne) SetName(v string) *ProtocolUpsertOne {
	return u.Update(func(s *ProtocolUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ProtocolUpsertOne) UpdateName() *ProtocolUpsertOne {
	return u.Update(func(s *ProtocolUpsert) {
		s.UpdateName()
	})
}

// SetDisplayName sets the "display_name" field.
func (u *ProtocolUpsertOne) SetDisplayName(v string) *ProtocolUpsertOne {
	return u.Update(func(s *ProtocolUpsert) {
		s.SetDisplayName(v)
	})
}

// UpdateDisplayName sets the "display_name" field to the value that was provided on create.
func (u *ProtocolUpsertOne) UpdateDisplayName() *ProtocolUpsertOne {
	return u.Update(func(s *ProtocolUpsert) {
		s.UpdateDisplayName()
	})
}

// SetPlatform sets the "platform" field.
func (u *ProtocolUpsertOne) SetPlatform(v string) *ProtocolUpsertOne {
	return u.Update(func(s *ProtocolUpsert) {
		s.SetPlatform(v)
	})
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *ProtocolUpsertOne) UpdatePlatform() *ProtocolUpsertOne {
	return u.Update(func(s *ProtocolUpsert) {
		s.UpdatePlatform()
	})
}

// SetGatewayEndpoint sets the "gateway_endpoint" field.
func (u *ProtocolUpsertOne) SetGatewayEndpoint(v string) *ProtocolUpsertOne {
	return u.Update(func(s *ProtocolUpsert) {
		s.SetGatewayEndpoint(v)
	})
}

// UpdateGatewayEndpoint sets the "gateway_endpoint" field to the value that was provided on create.
func (u *ProtocolUpsertOne) UpdateGatewayEndpoint() *ProtocolUpsertOne {
	return u.Update(func(s *ProtocolUpsert) {
		s.UpdateGatewayEndpoint()
	})
}

// SetIconSvg sets the "icon_svg" field.
func (u *ProtocolUpsertOne) SetIconSvg(v string) *ProtocolUpsertOne {
	return u.Update(func(s *ProtocolUpsert) {
		s.SetIconSvg(v)
	})
}

// UpdateIconSvg sets the "icon_svg" field to the value that was provided on create.
func (u *ProtocolUpsertOne) UpdateIconSvg() *ProtocolUpsertOne {
	return u.Update(func(s *ProtocolUpsert) {
		s.UpdateIconSvg()
	})
}

// ClearIconSvg clears the value of the "icon_svg" field.
func (u *ProtocolUpsertOne) ClearIconSvg() *ProtocolUpsertOne {
	return u.Update(func(s *ProtocolUpsert) {
		s.ClearIconSvg()
	})
}

// SetThemeColor sets the "theme_color" field.
func (u *ProtocolUpsertOne) SetThemeColor(v string) *ProtocolUpsertOne {
	return u.Update(func(s *ProtocolUpsert) {
		s.SetThemeColor(v)
	})
}

// UpdateThemeColor sets the "theme_color" field to the value that was provided on create.
func (u *ProtocolUpsertOne) UpdateThemeColor() *ProtocolUpsertOne {
	return u.Update(func(s *ProtocolUpsert) {
		s.UpdateThemeColor()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *ProtocolUpsertOne) SetSortOrder(v int) *ProtocolUpsertOne {
	return u.Update(func(s *ProtocolUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *ProtocolUpsertOne) AddSortOrder(v int) *ProtocolUpsertOne {
	return u.Update(func(s *ProtocolUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *ProtocolUpsertOne) UpdateSortOrder() *ProtocolUpsertOne {
	return u.Update(func(s *ProtocolUpsert) {
		s.UpdateSortOrder()
	})
}

// SetStatus sets the "status" field.
func (u *ProtocolUpsertOne) SetStatus(v string) *ProtocolUpsertOne {
	return u.Update(func(s *ProtocolUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ProtocolUpsertOne) UpdateStatus() *ProtocolUpsertOne {
	return u.Update(func(s *ProtocolUpsert) {
		s.UpdateStatus()
	})
}

// Exec executes the query.
func (u *ProtocolUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ProtocolCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ProtocolUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ProtocolUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ProtocolUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ProtocolCreateBulk is the builder for creating many Protocol entities in bulk.
type ProtocolCreateBulk struct {
	config
	err      error
	builders []*ProtocolCreate
	conflict []sql.ConflictOption
}

// Save creates the Protocol entities in the database.
func (_c *ProtocolCreateBulk) Save(ctx context.Context) ([]*Protocol, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Protocol, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProtocolMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ProtocolCreateBulk) SaveX(ctx context.Context) []*Protocol {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProtocolCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProtocolCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Protocol.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ProtocolUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ProtocolCreateBulk) OnConflict(opts ...sql.ConflictOption) *ProtocolUpsertBulk {
	_c.conflict = opts
	return &ProtocolUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Protocol.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ProtocolCreateBulk) OnConflictColumns(columns ...string) *ProtocolUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ProtocolUpsertBulk{
		create: _c,
	}
}

// ProtocolUpsertBulk is the builder for "upsert"-ing
// a bulk of Protocol nodes.
type ProtocolUpsertBulk struct {
	create *ProtocolCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Protocol.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ProtocolUpsertBulk) UpdateNewValues() *ProtocolUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(protocol.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Protocol.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ProtocolUpsertBulk) Ignore() *ProtocolUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ProtocolUpsertBulk) DoNothing() *ProtocolUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ProtocolCreateBulk.OnConflict
// documentation for more info.
func (u *ProtocolUpsertBulk) Update(set func(*ProtocolUpsert)) *ProtocolUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ProtocolUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ProtocolUpsertBulk) SetUpdatedAt(v time.Time) *ProtocolUpsertBulk {
	return u.Update(func(s *ProtocolUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ProtocolUpsertBulk) UpdateUpdatedAt() *ProtocolUpsertBulk {
	return u.Update(func(s *ProtocolUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetName sets the "name" field.
func (u *ProtocolUpsertBulk) SetName(v string) *ProtocolUpsertBulk {
	return u.Update(func(s *ProtocolUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ProtocolUpsertBulk) UpdateName() *ProtocolUpsertBulk {
	return u.Update(func(s *ProtocolUpsert) {
		s.UpdateName()
	})
}

// SetDisplayName sets the "display_name" field.
func (u *ProtocolUpsertBulk) SetDisplayName(v string) *ProtocolUpsertBulk {
	return u.Update(func(s *ProtocolUpsert) {
		s.SetDisplayName(v)
	})
}

// UpdateDisplayName sets the "display_name" field to the value that was provided on create.
func (u *ProtocolUpsertBulk) UpdateDisplayName() *ProtocolUpsertBulk {
	return u.Update(func(s *ProtocolUpsert) {
		s.UpdateDisplayName()
	})
}

// SetPlatform sets the "platform" field.
func (u *ProtocolUpsertBulk) SetPlatform(v string) *ProtocolUpsertBulk {
	return u.Update(func(s *ProtocolUpsert) {
		s.SetPlatform(v)
	})
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *ProtocolUpsertBulk) UpdatePlatform() *ProtocolUpsertBulk {
	return u.Update(func(s *ProtocolUpsert) {
		s.UpdatePlatform()
	})
}

// SetGatewayEndpoint sets the "gateway_endpoint" field.
func (u *ProtocolUpsertBulk) SetGatewayEndpoint(v string) *ProtocolUpsertBulk {
	return u.Update(func(s *ProtocolUpsert) {
		s.SetGatewayEndpoint(v)
	})
}

// UpdateGatewayEndpoint sets the "gateway_endpoint" field to the value that was provided on create.
func (u *ProtocolUpsertBulk) UpdateGatewayEndpoint() *ProtocolUpsertBulk {
	return u.Update(func(s *ProtocolUpsert) {
		s.UpdateGatewayEndpoint()
	})
}

// SetIconSvg sets the "icon_svg" field.
func (u *ProtocolUpsertBulk) SetIconSvg(v string) *ProtocolUpsertBulk {
	return u.Update(func(s *ProtocolUpsert) {
		s.SetIconSvg(v)
	})
}

// UpdateIconSvg sets the "icon_svg" field to the value that was provided on create.
func (u *ProtocolUpsertBulk) UpdateIconSvg() *ProtocolUpsertBulk {
	return u.Update(func(s *ProtocolUpsert) {
		s.UpdateIconSvg()
	})
}

// ClearIconSvg clears the value of the "icon_svg" field.
func (u *ProtocolUpsertBulk) ClearIconSvg() *ProtocolUpsertBulk {
	return u.Update(func(s *ProtocolUpsert) {
		s.ClearIconSvg()
	})
}

// SetThemeColor sets the "theme_color" field.
func (u *ProtocolUpsertBulk) SetThemeColor(v string) *ProtocolUpsertBulk {
	return u.Update(func(s *ProtocolUpsert) {
		s.SetThemeColor(v)
	})
}

// UpdateThemeColor sets the "theme_color" field to the value that was provided on create.
func (u *ProtocolUpsertBulk) UpdateThemeColor() *ProtocolUpsertBulk {
	return u.Update(func(s *ProtocolUpsert) {
		s.UpdateThemeColor()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *ProtocolUpsertBulk) SetSortOrder(v int) *ProtocolUpsertBulk {
	return u.Update(func(s *ProtocolUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *ProtocolUpsertBulk) AddSortOrder(v int) *ProtocolUpsertBulk {
	return u.Update(func(s *ProtocolUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *ProtocolUpsertBulk) UpdateSortOrder() *ProtocolUpsertBulk {
	return u.Update(func(s *ProtocolUpsert) {
		s.UpdateSortOrder()
	})
}

// SetStatus sets the "status" field.
func (u *ProtocolUpsertBulk) SetStatus(v string) *ProtocolUpsertBulk {
	return u.Update(func(s *ProtocolUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ProtocolUpsertBulk) UpdateStatus() *ProtocolUpsertBulk {
	return u.Update(func(s *ProtocolUpsert) {
		s.UpdateStatus()
	})
}

// Exec executes the query.
func (u *ProtocolUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ProtocolCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ProtocolCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ProtocolUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
