// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/userusagelimitrule"
)

// UserUsageLimitRuleUpdate is the builder for updating UserUsageLimitRule entities.
type UserUsageLimitRuleUpdate struct {
	config
	hooks    []Hook
	mutation *UserUsageLimitRuleMutation
}

// Where appends a list predicates to the UserUsageLimitRuleUpdate builder.
func (_u *UserUsageLimitRuleUpdate) Where(ps ...predicate.UserUsageLimitRule) *UserUsageLimitRuleUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserUsageLimitRuleUpdate) SetUpdatedAt(v time.Time) *UserUsageLimitRuleUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserUsageLimitRuleUpdate) SetUserID(v int64) *UserUsageLimitRuleUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserUsageLimitRuleUpdate) SetNillableUserID(v *int64) *UserUsageLimitRuleUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetGroupIds sets the "group_ids" field.
func (_u *UserUsageLimitRuleUpdate) SetGroupIds(v []int64) *UserUsageLimitRuleUpdate {
	_u.mutation.SetGroupIds(v)
	return _u
}

// AppendGroupIds appends value to the "group_ids" field.
func (_u *UserUsageLimitRuleUpdate) AppendGroupIds(v []int64) *UserUsageLimitRuleUpdate {
	_u.mutation.AppendGroupIds(v)
	return _u
}

// SetDailyLimitUsd sets the "daily_limit_usd" field.
func (_u *UserUsageLimitRuleUpdate) SetDailyLimitUsd(v float64) *UserUsageLimitRuleUpdate {
	_u.mutation.ResetDailyLimitUsd()
	_u.mutation.SetDailyLimitUsd(v)
	return _u
}

// SetNillableDailyLimitUsd sets the "daily_limit_usd" field if the given value is not nil.
func (_u *UserUsageLimitRuleUpdate) SetNillableDailyLimitUsd(v *float64) *UserUsageLimitRuleUpdate {
	if v != nil {
		_u.SetDailyLimitUsd(*v)
	}
	return _u
}

// AddDailyLimitUsd adds value to the "daily_limit_usd" field.
func (_u *UserUsageLimitRuleUpdate) AddDailyLimitUsd(v float64) *UserUsageLimitRuleUpdate {
	_u.mutation.AddDailyLimitUsd(v)
	return _u
}

// SetPeriod sets the "period" field.
func (_u *UserUsageLimitRuleUpdate) SetPeriod(v string) *UserUsageLimitRuleUpdate {
	_u.mutation.SetPeriod(v)
	return _u
}

// SetNillablePeriod sets the "period" field if the given value is not nil.
func (_u *UserUsageLimitRuleUpdate) SetNillablePeriod(v *string) *UserUsageLimitRuleUpdate {
	if v != nil {
		_u.SetPeriod(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *UserUsageLimitRuleUpdate) SetUser(v *User) *UserUsageLimitRuleUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the UserUsageLimitRuleMutation object of the builder.
func (_u *UserUsageLimitRuleUpdate) Mutation() *UserUsageLimitRuleMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *UserUsageLimitRuleUpdate) ClearUser() *UserUsageLimitRuleUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserUsageLimitRuleUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUsageLimitRuleUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserUsageLimitRuleUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUsageLimitRuleUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserUsageLimitRuleUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := userusagelimitrule.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserUsageLimitRuleUpdate) check() error {
	if v, ok := _u.mutation.Period(); ok {
		if err := userusagelimitrule.PeriodValidator(v); err != nil {
			return &ValidationError{Name: "period", err: fmt.Errorf(`ent: validator failed for field "UserUsageLimitRule.period": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserUsageLimitRule.user"`)
	}
	return nil
}

func (_u *UserUsageLimitRuleUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(userusagelimitrule.Table, userusagelimitrule.Columns, sqlgraph.NewFieldSpec(userusagelimitrule.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(userusagelimitrule.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.GroupIds(); ok {
		_spec.SetField(userusagelimitrule.FieldGroupIds, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedGroupIds(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, userusagelimitrule.FieldGroupIds, value)
		})
	}
	if value, ok := _u.mutation.DailyLimitUsd(); ok {
		_spec.SetField(userusagelimitrule.FieldDailyLimitUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDailyLimitUsd(); ok {
		_spec.AddField(userusagelimitrule.FieldDailyLimitUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Period(); ok {
		_spec.SetField(userusagelimitrule.FieldPeriod, field.TypeString, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userusagelimitrule.UserTable,
			Columns: []string{userusagelimitrule.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userusagelimitrule.UserTable,
			Columns: []string{userusagelimitrule.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userusagelimitrule.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserUsageLimitRuleUpdateOne is the builder for updating a single UserUsageLimitRule entity.
type UserUsageLimitRuleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserUsageLimitRuleMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserUsageLimitRuleUpdateOne) SetUpdatedAt(v time.Time) *UserUsageLimitRuleUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserUsageLimitRuleUpdateOne) SetUserID(v int64) *UserUsageLimitRuleUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserUsageLimitRuleUpdateOne) SetNillableUserID(v *int64) *UserUsageLimitRuleUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetGroupIds sets the "group_ids" field.
func (_u *UserUsageLimitRuleUpdateOne) SetGroupIds(v []int64) *UserUsageLimitRuleUpdateOne {
	_u.mutation.SetGroupIds(v)
	return _u
}

// AppendGroupIds appends value to the "group_ids" field.
func (_u *UserUsageLimitRuleUpdateOne) AppendGroupIds(v []int64) *UserUsageLimitRuleUpdateOne {
	_u.mutation.AppendGroupIds(v)
	return _u
}

// SetDailyLimitUsd sets the "daily_limit_usd" field.
func (_u *UserUsageLimitRuleUpdateOne) SetDailyLimitUsd(v float64) *UserUsageLimitRuleUpdateOne {
	_u.mutation.ResetDailyLimitUsd()
	_u.mutation.SetDailyLimitUsd(v)
	return _u
}

// SetNillableDailyLimitUsd sets the "daily_limit_usd" field if the given value is not nil.
func (_u *UserUsageLimitRuleUpdateOne) SetNillableDailyLimitUsd(v *float64) *UserUsageLimitRuleUpdateOne {
	if v != nil {
		_u.SetDailyLimitUsd(*v)
	}
	return _u
}

// AddDailyLimitUsd adds value to the "daily_limit_usd" field.
func (_u *UserUsageLimitRuleUpdateOne) AddDailyLimitUsd(v float64) *UserUsageLimitRuleUpdateOne {
	_u.mutation.AddDailyLimitUsd(v)
	return _u
}

// SetPeriod sets the "period" field.
func (_u *UserUsageLimitRuleUpdateOne) SetPeriod(v string) *UserUsageLimitRuleUpdateOne {
	_u.mutation.SetPeriod(v)
	return _u
}

// SetNillablePeriod sets the "period" field if the given value is not nil.
func (_u *UserUsageLimitRuleUpdateOne) SetNillablePeriod(v *string) *UserUsageLimitRuleUpdateOne {
	if v != nil {
		_u.SetPeriod(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *UserUsageLimitRuleUpdateOne) SetUser(v *User) *UserUsageLimitRuleUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the UserUsageLimitRuleMutation object of the builder.
func (_u *UserUsageLimitRuleUpdateOne) Mutation() *UserUsageLimitRuleMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *UserUsageLimitRuleUpdateOne) ClearUser() *UserUsageLimitRuleUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the UserUsageLimitRuleUpdate builder.
func (_u *UserUsageLimitRuleUpdateOne) Where(ps ...predicate.UserUsageLimitRule) *UserUsageLimitRuleUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserUsageLimitRuleUpdateOne) Select(field string, fields ...string) *UserUsageLimitRuleUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserUsageLimitRule entity.
func (_u *UserUsageLimitRuleUpdateOne) Save(ctx context.Context) (*UserUsageLimitRule, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUsageLimitRuleUpdateOne) SaveX(ctx context.Context) *UserUsageLimitRule {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserUsageLimitRuleUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUsageLimitRuleUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserUsageLimitRuleUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := userusagelimitrule.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserUsageLimitRuleUpdateOne) check() error {
	if v, ok := _u.mutation.Period(); ok {
		if err := userusagelimitrule.PeriodValidator(v); err != nil {
			return &ValidationError{Name: "period", err: fmt.Errorf(`ent: validator failed for field "UserUsageLimitRule.period": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserUsageLimitRule.user"`)
	}
	return nil
}

func (_u *UserUsageLimitRuleUpdateOne) sqlSave(ctx context.Context) (_node *UserUsageLimitRule, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(userusagelimitrule.Table, userusagelimitrule.Columns, sqlgraph.NewFieldSpec(userusagelimitrule.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserUsageLimitRule.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userusagelimitrule.FieldID)
		for _, f := range fields {
			if !userusagelimitrule.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != userusagelimitrule.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(userusagelimitrule.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.GroupIds(); ok {
		_spec.SetField(userusagelimitrule.FieldGroupIds, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedGroupIds(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, userusagelimitrule.FieldGroupIds, value)
		})
	}
	if value, ok := _u.mutation.DailyLimitUsd(); ok {
		_spec.SetField(userusagelimitrule.FieldDailyLimitUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDailyLimitUsd(); ok {
		_spec.AddField(userusagelimitrule.FieldDailyLimitUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Period(); ok {
		_spec.SetField(userusagelimitrule.FieldPeriod, field.TypeString, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userusagelimitrule.UserTable,
			Columns: []string{userusagelimitrule.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userusagelimitrule.UserTable,
			Columns: []string{userusagelimitrule.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UserUsageLimitRule{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userusagelimitrule.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
