// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/userusagelimitrule"
)

// UserUsageLimitRule is the model entity for the UserUsageLimitRule schema.
type UserUsageLimitRule struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// 命中分组 ID 列表（非空，元素去重）；规则间 group_ids 禁止重叠
	GroupIds []int64 `json:"group_ids,omitempty"`
	// 本规则下每日限额（USD）
	DailyLimitUsd float64 `json:"daily_limit_usd,omitempty"`
	// 扩展占位：daily / weekly / monthly；首版只支持 daily
	Period string `json:"period,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserUsageLimitRuleQuery when eager-loading is set.
	Edges        UserUsageLimitRuleEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UserUsageLimitRuleEdges holds the relations/edges for other nodes in the graph.
type UserUsageLimitRuleEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserUsageLimitRuleEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserUsageLimitRule) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case userusagelimitrule.FieldGroupIds:
			values[i] = new([]byte)
		case userusagelimitrule.FieldDailyLimitUsd:
			values[i] = new(sql.NullFloat64)
		case userusagelimitrule.FieldID, userusagelimitrule.FieldUserID:
			values[i] = new(sql.NullInt64)
		case userusagelimitrule.FieldPeriod:
			values[i] = new(sql.NullString)
		case userusagelimitrule.FieldCreatedAt, userusagelimitrule.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserUsageLimitRule fields.
func (_m *UserUsageLimitRule) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case userusagelimitrule.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case userusagelimitrule.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case userusagelimitrule.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case userusagelimitrule.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case userusagelimitrule.FieldGroupIds:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field group_ids", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.GroupIds); err != nil {
					return fmt.Errorf("unmarshal field group_ids: %w", err)
				}
			}
		case userusagelimitrule.FieldDailyLimitUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field daily_limit_usd", values[i])
			} else if value.Valid {
				_m.DailyLimitUsd = value.Float64
			}
		case userusagelimitrule.FieldPeriod:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field period", values[i])
			} else if value.Valid {
				_m.Period = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UserUsageLimitRule.
// This includes values selected through modifiers, order, etc.
func (_m *UserUsageLimitRule) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the UserUsageLimitRule entity.
func (_m *UserUsageLimitRule) QueryUser() *UserQuery {
	return NewUserUsageLimitRuleClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this UserUsageLimitRule.
// Note that you need to call UserUsageLimitRule.Unwrap() before calling this method if this UserUsageLimitRule
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UserUsageLimitRule) Update() *UserUsageLimitRuleUpdateOne {
	return NewUserUsageLimitRuleClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UserUsageLimitRule entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UserUsageLimitRule) Unwrap() *UserUsageLimitRule {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UserUsageLimitRule is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UserUsageLimitRule) String() string {
	var builder strings.Builder
	builder.WriteString("UserUsageLimitRule(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("group_ids=")
	builder.WriteString(fmt.Sprintf("%v", _m.GroupIds))
	builder.WriteString(", ")
	builder.WriteString("daily_limit_usd=")
	builder.WriteString(fmt.Sprintf("%v", _m.DailyLimitUsd))
	builder.WriteString(", ")
	builder.WriteString("period=")
	builder.WriteString(_m.Period)
	builder.WriteByte(')')
	return builder.String()
}

// UserUsageLimitRules is a parsable slice of UserUsageLimitRule.
type UserUsageLimitRules []*UserUsageLimitRule
