// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/userusagelimitrule"
)

// UserUsageLimitRuleCreate is the builder for creating a UserUsageLimitRule entity.
type UserUsageLimitRuleCreate struct {
	config
	mutation *UserUsageLimitRuleMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *UserUsageLimitRuleCreate) SetCreatedAt(v time.Time) *UserUsageLimitRuleCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UserUsageLimitRuleCreate) SetNillableCreatedAt(v *time.Time) *UserUsageLimitRuleCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UserUsageLimitRuleCreate) SetUpdatedAt(v time.Time) *UserUsageLimitRuleCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UserUsageLimitRuleCreate) SetNillableUpdatedAt(v *time.Time) *UserUsageLimitRuleCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *UserUsageLimitRuleCreate) SetUserID(v int64) *UserUsageLimitRuleCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetGroupIds sets the "group_ids" field.
func (_c *UserUsageLimitRuleCreate) SetGroupIds(v []int64) *UserUsageLimitRuleCreate {
	_c.mutation.SetGroupIds(v)
	return _c
}

// SetDailyLimitUsd sets the "daily_limit_usd" field.
func (_c *UserUsageLimitRuleCreate) SetDailyLimitUsd(v float64) *UserUsageLimitRuleCreate {
	_c.mutation.SetDailyLimitUsd(v)
	return _c
}

// SetPeriod sets the "period" field.
func (_c *UserUsageLimitRuleCreate) SetPeriod(v string) *UserUsageLimitRuleCreate {
	_c.mutation.SetPeriod(v)
	return _c
}

// SetNillablePeriod sets the "period" field if the given value is not nil.
func (_c *UserUsageLimitRuleCreate) SetNillablePeriod(v *string) *UserUsageLimitRuleCreate {
	if v != nil {
		_c.SetPeriod(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *UserUsageLimitRuleCreate) SetUser(v *User) *UserUsageLimitRuleCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the UserUsageLimitRuleMutation object of the builder.
func (_c *UserUsageLimitRuleCreate) Mutation() *UserUsageLimitRuleMutation {
	return _c.mutation
}

// Save creates the UserUsageLimitRule in the database.
func (_c *UserUsageLimitRuleCreate) Save(ctx context.Context) (*UserUsageLimitRule, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserUsageLimitRuleCreate) SaveX(ctx context.Context) *UserUsageLimitRule {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserUsageLimitRuleCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserUsageLimitRuleCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserUsageLimitRuleCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := userusagelimitrule.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := userusagelimitrule.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Period(); !ok {
		v := userusagelimitrule.DefaultPeriod
		_c.mutation.SetPeriod(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserUsageLimitRuleCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UserUsageLimitRule.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "UserUsageLimitRule.updated_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "UserUsageLimitRule.user_id"`)}
	}
	if _, ok := _c.mutation.GroupIds(); !ok {
		return &ValidationError{Name: "group_ids", err: errors.New(`ent: missing required field "UserUsageLimitRule.group_ids"`)}
	}
	if _, ok := _c.mutation.DailyLimitUsd(); !ok {
		return &ValidationError{Name: "daily_limit_usd", err: errors.New(`ent: missing required field "UserUsageLimitRule.daily_limit_usd"`)}
	}
	if _, ok := _c.mutation.Period(); !ok {
		return &ValidationError{Name: "period", err: errors.New(`ent: missing required field "UserUsageLimitRule.period"`)}
	}
	if v, ok := _c.mutation.Period(); ok {
		if err := userusagelimitrule.PeriodValidator(v); err != nil {
			return &ValidationError{Name: "period", err: fmt.Errorf(`ent: validator failed for field "UserUsageLimitRule.period": %w`, err)}
		}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "UserUsageLimitRule.user"`)}
	}
	return nil
}

func (_c *UserUsageLimitRuleCreate) sqlSave(ctx context.Context) (*UserUsageLimitRule, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserUsageLimitRuleCreate) createSpec() (*UserUsageLimitRule, *sqlgraph.CreateSpec) {
	var (
		_node = &UserUsageLimitRule{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(userusagelimitrule.Table, sqlgraph.NewFieldSpec(userusagelimitrule.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(userusagelimitrule.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(userusagelimitrule.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.GroupIds(); ok {
		_spec.SetField(userusagelimitrule.FieldGroupIds, field.TypeJSON, value)
		_node.GroupIds = value
	}
	if value, ok := _c.mutation.DailyLimitUsd(); ok {
		_spec.SetField(userusagelimitrule.FieldDailyLimitUsd, field.TypeFloat64, value)
		_node.DailyLimitUsd = value
	}
	if value, ok := _c.mutation.Period(); ok {
		_spec.SetField(userusagelimitrule.FieldPeriod, field.TypeString, value)
		_node.Period = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userusagelimitrule.UserTable,
			Columns: []string{userusagelimitrule.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserUsageLimitRule.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserUsageLimitRuleUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *UserUsageLimitRuleCreate) OnConflict(opts ...sql.ConflictOption) *UserUsageLimitRuleUpsertOne {
	_c.conflict = opts
	return &UserUsageLimitRuleUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserUsageLimitRule.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserUsageLimitRuleCreate) OnConflictColumns(columns ...string) *UserUsageLimitRuleUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserUsageLimitRuleUpsertOne{
		create: _c,
	}
}

type (
	// UserUsageLimitRuleUpsertOne is the builder for "upsert"-ing
	//  one UserUsageLimitRule node.
	UserUsageLimitRuleUpsertOne struct {
		create *UserUsageLimitRuleCreate
	}

	// UserUsageLimitRuleUpsert is the "OnConflict" setter.
	UserUsageLimitRuleUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *UserUsageLimitRuleUpsert) SetUpdatedAt(v time.Time) *UserUsageLimitRuleUpsert {
	u.Set(userusagelimitrule.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserUsageLimitRuleUpsert) UpdateUpdatedAt() *UserUsageLimitRuleUpsert {
	u.SetExcluded(userusagelimitrule.FieldUpdatedAt)
	return u
}

// SetUserID sets the "user_id" field.
func (u *UserUsageLimitRuleUpsert) SetUserID(v int64) *UserUsageLimitRuleUpsert {
	u.Set(userusagelimitrule.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserUsageLimitRuleUpsert) UpdateUserID() *UserUsageLimitRuleUpsert {
	u.SetExcluded(userusagelimitrule.FieldUserID)
	return u
}

// SetGroupIds sets the "group_ids" field.
func (u *UserUsageLimitRuleUpsert) SetGroupIds(v []int64) *UserUsageLimitRuleUpsert {
	u.Set(userusagelimitrule.FieldGroupIds, v)
	return u
}

// UpdateGroupIds sets the "group_ids" field to the value that was provided on create.
func (u *UserUsageLimitRuleUpsert) UpdateGroupIds() *UserUsageLimitRuleUpsert {
	u.SetExcluded(userusagelimitrule.FieldGroupIds)
	return u
}

// SetDailyLimitUsd sets the "daily_limit_usd" field.
func (u *UserUsageLimitRuleUpsert) SetDailyLimitUsd(v float64) *UserUsageLimitRuleUpsert {
	u.Set(userusagelimitrule.FieldDailyLimitUsd, v)
	return u
}

// UpdateDailyLimitUsd sets the "daily_limit_usd" field to the value that was provided on create.
func (u *UserUsageLimitRuleUpsert) UpdateDailyLimitUsd() *UserUsageLimitRuleUpsert {
	u.SetExcluded(userusagelimitrule.FieldDailyLimitUsd)
	return u
}

// AddDailyLimitUsd adds v to the "daily_limit_usd" field.
func (u *UserUsageLimitRuleUpsert) AddDailyLimitUsd(v float64) *UserUsageLimitRuleUpsert {
	u.Add(userusagelimitrule.FieldDailyLimitUsd, v)
	return u
}

// SetPeriod sets the "period" field.
func (u *UserUsageLimitRuleUpsert) SetPeriod(v string) *UserUsageLimitRuleUpsert {
	u.Set(userusagelimitrule.FieldPeriod, v)
	return u
}

// UpdatePeriod sets the "period" field to the value that was provided on create.
func (u *UserUsageLimitRuleUpsert) UpdatePeriod() *UserUsageLimitRuleUpsert {
	u.SetExcluded(userusagelimitrule.FieldPeriod)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.UserUsageLimitRule.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserUsageLimitRuleUpsertOne) UpdateNewValues() *UserUsageLimitRuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(userusagelimitrule.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserUsageLimitRule.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UserUsageLimitRuleUpsertOne) Ignore() *UserUsageLimitRuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserUsageLimitRuleUpsertOne) DoNothing() *UserUsageLimitRuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserUsageLimitRuleCreate.OnConflict
// documentation for more info.
func (u *UserUsageLimitRuleUpsertOne) Update(set func(*UserUsageLimitRuleUpsert)) *UserUsageLimitRuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserUsageLimitRuleUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserUsageLimitRuleUpsertOne) SetUpdatedAt(v time.Time) *UserUsageLimitRuleUpsertOne {
	return u.Update(func(s *UserUsageLimitRuleUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserUsageLimitRuleUpsertOne) UpdateUpdatedAt() *UserUsageLimitRuleUpsertOne {
	return u.Update(func(s *UserUsageLimitRuleUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *UserUsageLimitRuleUpsertOne) SetUserID(v int64) *UserUsageLimitRuleUpsertOne {
	return u.Update(func(s *UserUsageLimitRuleUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserUsageLimitRuleUpsertOne) UpdateUserID() *UserUsageLimitRuleUpsertOne {
	return u.Update(func(s *UserUsageLimitRuleUpsert) {
		s.UpdateUserID()
	})
}

// SetGroupIds sets the "group_ids" field.
func (u *UserUsageLimitRuleUpsertOne) SetGroupIds(v []int64) *UserUsageLimitRuleUpsertOne {
	return u.Update(func(s *UserUsageLimitRuleUpsert) {
		s.SetGroupIds(v)
	})
}

// UpdateGroupIds sets the "group_ids" field to the value that was provided on create.
func (u *UserUsageLimitRuleUpsertOne) UpdateGroupIds() *UserUsageLimitRuleUpsertOne {
	return u.Update(func(s *UserUsageLimitRuleUpsert) {
		s.UpdateGroupIds()
	})
}

// SetDailyLimitUsd sets the "daily_limit_usd" field.
func (u *UserUsageLimitRuleUpsertOne) SetDailyLimitUsd(v float64) *UserUsageLimitRuleUpsertOne {
	return u.Update(func(s *UserUsageLimitRuleUpsert) {
		s.SetDailyLimitUsd(v)
	})
}

// AddDailyLimitUsd adds v to the "daily_limit_usd" field.
func (u *UserUsageLimitRuleUpsertOne) AddDailyLimitUsd(v float64) *UserUsageLimitRuleUpsertOne {
	return u.Update(func(s *UserUsageLimitRuleUpsert) {
		s.AddDailyLimitUsd(v)
	})
}

// UpdateDailyLimitUsd sets the "daily_limit_usd" field to the value that was provided on create.
func (u *UserUsageLimitRuleUpsertOne) UpdateDailyLimitUsd() *UserUsageLimitRuleUpsertOne {
	return u.Update(func(s *UserUsageLimitRuleUpsert) {
		s.UpdateDailyLimitUsd()
	})
}

// SetPeriod sets the "period" field.
func (u *UserUsageLimitRuleUpsertOne) SetPeriod(v string) *UserUsageLimitRuleUpsertOne {
	return u.Update(func(s *UserUsageLimitRuleUpsert) {
		s.SetPeriod(v)
	})
}

// UpdatePeriod sets the "period" field to the value that was provided on create.
func (u *UserUsageLimitRuleUpsertOne) UpdatePeriod() *UserUsageLimitRuleUpsertOne {
	return u.Update(func(s *UserUsageLimitRuleUpsert) {
		s.UpdatePeriod()
	})
}

// Exec executes the query.
func (u *UserUsageLimitRuleUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserUsageLimitRuleCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserUsageLimitRuleUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UserUsageLimitRuleUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UserUsageLimitRuleUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UserUsageLimitRuleCreateBulk is the builder for creating many UserUsageLimitRule entities in bulk.
type UserUsageLimitRuleCreateBulk struct {
	config
	err      error
	builders []*UserUsageLimitRuleCreate
	conflict []sql.ConflictOption
}

// Save creates the UserUsageLimitRule entities in the database.
func (_c *UserUsageLimitRuleCreateBulk) Save(ctx context.Context) ([]*UserUsageLimitRule, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UserUsageLimitRule, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserUsageLimitRuleMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserUsageLimitRuleCreateBulk) SaveX(ctx context.Context) []*UserUsageLimitRule {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserUsageLimitRuleCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserUsageLimitRuleCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserUsageLimitRule.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserUsageLimitRuleUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *UserUsageLimitRuleCreateBulk) OnConflict(opts ...sql.ConflictOption) *UserUsageLimitRuleUpsertBulk {
	_c.conflict = opts
	return &UserUsageLimitRuleUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserUsageLimitRule.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserUsageLimitRuleCreateBulk) OnConflictColumns(columns ...string) *UserUsageLimitRuleUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserUsageLimitRuleUpsertBulk{
		create: _c,
	}
}

// UserUsageLimitRuleUpsertBulk is the builder for "upsert"-ing
// a bulk of UserUsageLimitRule nodes.
type UserUsageLimitRuleUpsertBulk struct {
	create *UserUsageLimitRuleCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UserUsageLimitRule.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserUsageLimitRuleUpsertBulk) UpdateNewValues() *UserUsageLimitRuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(userusagelimitrule.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserUsageLimitRule.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UserUsageLimitRuleUpsertBulk) Ignore() *UserUsageLimitRuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserUsageLimitRuleUpsertBulk) DoNothing() *UserUsageLimitRuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserUsageLimitRuleCreateBulk.OnConflict
// documentation for more info.
func (u *UserUsageLimitRuleUpsertBulk) Update(set func(*UserUsageLimitRuleUpsert)) *UserUsageLimitRuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserUsageLimitRuleUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserUsageLimitRuleUpsertBulk) SetUpdatedAt(v time.Time) *UserUsageLimitRuleUpsertBulk {
	return u.Update(func(s *UserUsageLimitRuleUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserUsageLimitRuleUpsertBulk) UpdateUpdatedAt() *UserUsageLimitRuleUpsertBulk {
	return u.Update(func(s *UserUsageLimitRuleUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *UserUsageLimitRuleUpsertBulk) SetUserID(v int64) *UserUsageLimitRuleUpsertBulk {
	return u.Update(func(s *UserUsageLimitRuleUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserUsageLimitRuleUpsertBulk) UpdateUserID() *UserUsageLimitRuleUpsertBulk {
	return u.Update(func(s *UserUsageLimitRuleUpsert) {
		s.UpdateUserID()
	})
}

// SetGroupIds sets the "group_ids" field.
func (u *UserUsageLimitRuleUpsertBulk) SetGroupIds(v []int64) *UserUsageLimitRuleUpsertBulk {
	return u.Update(func(s *UserUsageLimitRuleUpsert) {
		s.SetGroupIds(v)
	})
}

// UpdateGroupIds sets the "group_ids" field to the value that was provided on create.
func (u *UserUsageLimitRuleUpsertBulk) UpdateGroupIds() *UserUsageLimitRuleUpsertBulk {
	return u.Update(func(s *UserUsageLimitRuleUpsert) {
		s.UpdateGroupIds()
	})
}

// SetDailyLimitUsd sets the "daily_limit_usd" field.
func (u *UserUsageLimitRuleUpsertBulk) SetDailyLimitUsd(v float64) *UserUsageLimitRuleUpsertBulk {
	return u.Update(func(s *UserUsageLimitRuleUpsert) {
		s.SetDailyLimitUsd(v)
	})
}

// AddDailyLimitUsd adds v to the "daily_limit_usd" field.
func (u *UserUsageLimitRuleUpsertBulk) AddDailyLimitUsd(v float64) *UserUsageLimitRuleUpsertBulk {
	return u.Update(func(s *UserUsageLimitRuleUpsert) {
		s.AddDailyLimitUsd(v)
	})
}

// UpdateDailyLimitUsd sets the "daily_limit_usd" field to the value that was provided on create.
func (u *UserUsageLimitRuleUpsertBulk) UpdateDailyLimitUsd() *UserUsageLimitRuleUpsertBulk {
	return u.Update(func(s *UserUsageLimitRuleUpsert) {
		s.UpdateDailyLimitUsd()
	})
}

// SetPeriod sets the "period" field.
func (u *UserUsageLimitRuleUpsertBulk) SetPeriod(v string) *UserUsageLimitRuleUpsertBulk {
	return u.Update(func(s *UserUsageLimitRuleUpsert) {
		s.SetPeriod(v)
	})
}

// UpdatePeriod sets the "period" field to the value that was provided on create.
func (u *UserUsageLimitRuleUpsertBulk) UpdatePeriod() *UserUsageLimitRuleUpsertBulk {
	return u.Update(func(s *UserUsageLimitRuleUpsert) {
		s.UpdatePeriod()
	})
}

// Exec executes the query.
func (u *UserUsageLimitRuleUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UserUsageLimitRuleCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserUsageLimitRuleCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserUsageLimitRuleUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
