// Code generated by ent, DO NOT EDIT.

package protocol

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.Protocol {
	return predicate.Protocol(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.Protocol {
	return predicate.Protocol(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.Protocol {
	return predicate.Protocol(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.Protocol {
	return predicate.Protocol(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.Protocol {
	return predicate.Protocol(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.Protocol {
	return predicate.Protocol(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.Protocol {
	return predicate.Protocol(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.Protocol {
	return predicate.Protocol(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.Protocol {
	return predicate.Protocol(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Protocol {
	return predicate.Protocol(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Protocol {
	return predicate.Protocol(sql.FieldEQ(FieldUpdatedAt, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Protocol {
	return predicate.Protocol(sql.FieldEQ(FieldName, v))
}

// DisplayName applies equality check predicate on the "display_name" field. It's identical to DisplayNameEQ.
func DisplayName(v string) predicate.Protocol {
	return predicate.Protocol(sql.FieldEQ(FieldDisplayName, v))
}

// Platform applies equality check predicate on the "platform" field. It's identical to PlatformEQ.
func Platform(v string) predicate.Protocol {
	return predicate.Protocol(sql.FieldEQ(FieldPlatform, v))
}

// GatewayEndpoint applies equality check predicate on the "gateway_endpoint" field. It's identical to GatewayEndpointEQ.
func GatewayEndpoint(v string) predicate.Protocol {
	return predicate.Protocol(sql.FieldEQ(FieldGatewayEndpoint, v))
}

// IconSvg applies equality check predicate on the "icon_svg" field. It's identical to IconSvgEQ.
func IconSvg(v string) predicate.Protocol {
	return predicate.Protocol(sql.FieldEQ(FieldIconSvg, v))
}

// ThemeColor applies equality check predicate on the "theme_color" field. It's identical to ThemeColorEQ.
func ThemeColor(v string) predicate.Protocol {
	return predicate.Protocol(sql.FieldEQ(FieldThemeColor, v))
}

// SortOrder applies equality check predicate on the "sort_order" field. It's identical to SortOrderEQ.
func SortOrder(v int) predicate.Protocol {
	return predicate.Protocol(sql.FieldEQ(FieldSortOrder, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.Protocol {
	return predicate.Protocol(sql.FieldEQ(FieldStatus, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Protocol {
	return predicate.Protocol(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Protocol {
	return predicate.Protocol(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Protocol {
	return predicate.Protocol(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Protocol {
	return predicate.Protocol(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Protocol {
	return predicate.Protocol(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Protocol {
	return predicate.Protocol(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Protocol {
	return predicate.Protocol(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Protocol {
	return predicate.Protocol(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Protocol {
	return predicate.Protocol(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Protocol {
	return predicate.Protocol(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Protocol {
	return predicate.Protocol(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Protocol {
	return predicate.Protocol(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Protocol {
	return predicate.Protocol(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Protocol {
	return predicate.Protocol(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Protocol {
	return predicate.Protocol(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Protocol {
	return predicate.Protocol(sql.FieldLTE(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Protocol {
	return predicate.Protocol(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Protocol {
	return predicate.Protocol(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Protocol {
	return predicate.Protocol(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Protocol {
	return predicate.Protocol(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Protocol {
	return predicate.Protocol(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Protocol {
	return predicate.Protocol(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Protocol {
	return predicate.Protocol(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Protocol {
	return predicate.Protocol(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Protocol {
	return predicate.Protocol(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Protocol {
	return predicate.Protocol(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Protocol {
	return predicate.Protocol(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Protocol {
	return predicate.Protocol(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Protocol {
	return predicate.Protocol(sql.FieldContainsFold(FieldName, v))
}

// DisplayNameEQ applies the EQ predicate on the "display_name" field.
func DisplayNameEQ(v string) predicate.Protocol {
	return predicate.Protocol(sql.FieldEQ(FieldDisplayName, v))
}

// DisplayNameNEQ applies the NEQ predicate on the "display_name" field.
func DisplayNameNEQ(v string) predicate.Protocol {
	return predicate.Protocol(sql.FieldNEQ(FieldDisplayName, v))
}

// DisplayNameIn applies the In predicate on the "display_name" field.
func DisplayNameIn(vs ...string) predicate.Protocol {
	return predicate.Protocol(sql.FieldIn(FieldDisplayName, vs...))
}

// DisplayNameNotIn applies the NotIn predicate on the "display_name" field.
func DisplayNameNotIn(vs ...string) predicate.Protocol {
	return predicate.Protocol(sql.FieldNotIn(FieldDisplayName, vs...))
}

// DisplayNameGT applies the GT predicate on the "display_name" field.
func DisplayNameGT(v string) predicate.Protocol {
	return predicate.Protocol(sql.FieldGT(FieldDisplayName, v))
}

// DisplayNameGTE applies the GTE predicate on the "display_name" field.
func DisplayNameGTE(v string) predicate.Protocol {
	return predicate.Protocol(sql.FieldGTE(FieldDisplayName, v))
}

// DisplayNameLT applies the LT predicate on the "display_name" field.
func DisplayNameLT(v string) predicate.Protocol {
	return predicate.Protocol(sql.FieldLT(FieldDisplayName, v))
}

// DisplayNameLTE applies the LTE predicate on the "display_name" field.
func DisplayNameLTE(v string) predicate.Protocol {
	return predicate.Protocol(sql.FieldLTE(FieldDisplayName, v))
}

// DisplayNameContains applies the Contains predicate on the "display_name" field.
func DisplayNameContains(v string) predicate.Protocol {
	return predicate.Protocol(sql.FieldContains(FieldDisplayName, v))
}

// DisplayNameHasPrefix applies the HasPrefix predicate on the "display_name" field.
func DisplayNameHasPrefix(v string) predicate.Protocol {
	return predicate.Protocol(sql.FieldHasPrefix(FieldDisplayName, v))
}

// DisplayNameHasSuffix applies the HasSuffix predicate on the "display_name" field.
func DisplayNameHasSuffix(v string) predicate.Protocol {
	return predicate.Protocol(sql.FieldHasSuffix(FieldDisplayName, v))
}

// DisplayNameEqualFold applies the EqualFold predicate on the "display_name" field.
func DisplayNameEqualFold(v string) predicate.Protocol {
	return predicate.Protocol(sql.FieldEqualFold(FieldDisplayName, v))
}

// DisplayNameContainsFold applies the ContainsFold predicate on the "display_name" field.
func DisplayNameContainsFold(v string) predicate.Protocol {
	return predicate.Protocol(sql.FieldContainsFold(FieldDisplayName, v))
}

// PlatformEQ applies the EQ predicate on the "platform" field.
func PlatformEQ(v string) predicate.Protocol {
	return predicate.Protocol(sql.FieldEQ(FieldPlatform, v))
}

// PlatformNEQ applies the NEQ predicate on the "platform" field.
func PlatformNEQ(v string) predicate.Protocol {
	return predicate.Protocol(sql.FieldNEQ(FieldPlatform, v))
}

// PlatformIn applies the In predicate on the "platform" field.
func PlatformIn(vs ...string) predicate.Protocol {
	return predicate.Protocol(sql.FieldIn(FieldPlatform, vs...))
}

// PlatformNotIn applies the NotIn predicate on the "platform" field.
func PlatformNotIn(vs ...string) predicate.Protocol {
	return predicate.Protocol(sql.FieldNotIn(FieldPlatform, vs...))
}

// PlatformGT applies the GT predicate on the "platform" field.
func PlatformGT(v string) predicate.Protocol {
	return predicate.Protocol(sql.FieldGT(FieldPlatform, v))
}

// PlatformGTE applies the GTE predicate on the "platform" field.
func PlatformGTE(v string) predicate.Protocol {
	return predicate.Protocol(sql.FieldGTE(FieldPlatform, v))
}

// PlatformLT applies the LT predicate on the "platform" field.
func PlatformLT(v string) predicate.Protocol {
	return predicate.Protocol(sql.FieldLT(FieldPlatform, v))
}

// PlatformLTE applies the LTE predicate on the "platform" field.
func PlatformLTE(v string) predicate.Protocol {
	return predicate.Protocol(sql.FieldLTE(FieldPlatform, v))
}

// PlatformContains applies the Contains predicate on the "platform" field.
func PlatformContains(v string) predicate.Protocol {
	return predicate.Protocol(sql.FieldContains(FieldPlatform, v))
}

// PlatformHasPrefix applies the HasPrefix predicate on the "platform" field.
func PlatformHasPrefix(v string) predicate.Protocol {
	return predicate.Protocol(sql.FieldHasPrefix(FieldPlatform, v))
}

// PlatformHasSuffix applies the HasSuffix predicate on the "platform" field.
func PlatformHasSuffix(v string) predicate.Protocol {
	return predicate.Protocol(sql.FieldHasSuffix(FieldPlatform, v))
}

// PlatformEqualFold applies the EqualFold predicate on the "platform" field.
func PlatformEqualFold(v string) predicate.Protocol {
	return predicate.Protocol(sql.FieldEqualFold(FieldPlatform, v))
}

// PlatformContainsFold applies the ContainsFold predicate on the "platform" field.
func PlatformContainsFold(v string) predicate.Protocol {
	return predicate.Protocol(sql.FieldContainsFold(FieldPlatform, v))
}

// GatewayEndpointEQ applies the EQ predicate on the "gateway_endpoint" field.
func GatewayEndpointEQ(v string) predicate.Protocol {
	return predicate.Protocol(sql.FieldEQ(FieldGatewayEndpoint, v))
}

// GatewayEndpointNEQ applies the NEQ predicate on the "gateway_endpoint" field.
func GatewayEndpointNEQ(v string) predicate.Protocol {
	return predicate.Protocol(sql.FieldNEQ(FieldGatewayEndpoint, v))
}

// GatewayEndpointIn applies the In predicate on the "gateway_endpoint" field.
func GatewayEndpointIn(vs ...string) predicate.Protocol {
	return predicate.Protocol(sql.FieldIn(FieldGatewayEndpoint, vs...))
}

// GatewayEndpointNotIn applies the NotIn predicate on the "gateway_endpoint" field.
func GatewayEndpointNotIn(vs ...string) predicate.Protocol {
	return predicate.Protocol(sql.FieldNotIn(FieldGatewayEndpoint, vs...))
}

// GatewayEndpointGT applies the GT predicate on the "gateway_endpoint" field.
func GatewayEndpointGT(v string) predicate.Protocol {
	return predicate.Protocol(sql.FieldGT(FieldGatewayEndpoint, v))
}

// GatewayEndpointGTE applies the GTE predicate on the "gateway_endpoint" field.
func GatewayEndpointGTE(v string) predicate.Protocol {
	return predicate.Protocol(sql.FieldGTE(FieldGatewayEndpoint, v))
}

// GatewayEndpointLT applies the LT predicate on the "gateway_endpoint" field.
func GatewayEndpointLT(v string) predicate.Protocol {
	return predicate.Protocol(sql.FieldLT(FieldGatewayEndpoint, v))
}

// GatewayEndpointLTE applies the LTE predicate on the "gateway_endpoint" field.
func GatewayEndpointLTE(v string) predicate.Protocol {
	return predicate.Protocol(sql.FieldLTE(FieldGatewayEndpoint, v))
}

// GatewayEndpointContains applies the Contains predicate on the "gateway_endpoint" field.
func GatewayEndpointContains(v string) predicate.Protocol {
	return predicate.Protocol(sql.FieldContains(FieldGatewayEndpoint, v))
}

// GatewayEndpointHasPrefix applies the HasPrefix predicate on the "gateway_endpoint" field.
func GatewayEndpointHasPrefix(v string) predicate.Protocol {
	return predicate.Protocol(sql.FieldHasPrefix(FieldGatewayEndpoint, v))
}

// GatewayEndpointHasSuffix applies the HasSuffix predicate on the "gateway_endpoint" field.
func GatewayEndpointHasSuffix(v string) predicate.Protocol {
	return predicate.Protocol(sql.FieldHasSuffix(FieldGatewayEndpoint, v))
}

// GatewayEndpointEqualFold applies the EqualFold predicate on the "gateway_endpoint" field.
func GatewayEndpointEqualFold(v string) predicate.Protocol {
	return predicate.Protocol(sql.FieldEqualFold(FieldGatewayEndpoint, v))
}

// GatewayEndpointContainsFold applies the ContainsFold predicate on the "gateway_endpoint" field.
func GatewayEndpointContainsFold(v string) predicate.Protocol {
	return predicate.Protocol(sql.FieldContainsFold(FieldGatewayEndpoint, v))
}

// IconSvgEQ applies the EQ predicate on the "icon_svg" field.
func IconSvgEQ(v string) predicate.Protocol {
	return predicate.Protocol(sql.FieldEQ(FieldIconSvg, v))
}

// IconSvgNEQ applies the NEQ predicate on the "icon_svg" field.
func IconSvgNEQ(v string) predicate.Protocol {
	return predicate.Protocol(sql.FieldNEQ(FieldIconSvg, v))
}

// IconSvgIn applies the In predicate on the "icon_svg" field.
func IconSvgIn(vs ...string) predicate.Protocol {
	return predicate.Protocol(sql.FieldIn(FieldIconSvg, vs...))
}

// IconSvgNotIn applies the NotIn predicate on the "icon_svg" field.
func IconSvgNotIn(vs ...string) predicate.Protocol {
	return predicate.Protocol(sql.FieldNotIn(FieldIconSvg, vs...))
}

// IconSvgGT applies the GT predicate on the "icon_svg" field.
func IconSvgGT(v string) predicate.Protocol {
	return predicate.Protocol(sql.FieldGT(FieldIconSvg, v))
}

// IconSvgGTE applies the GTE predicate on the "icon_svg" field.
func IconSvgGTE(v string) predicate.Protocol {
	return predicate.Protocol(sql.FieldGTE(FieldIconSvg, v))
}

// IconSvgLT applies the LT predicate on the "icon_svg" field.
func IconSvgLT(v string) predicate.Protocol {
	return predicate.Protocol(sql.FieldLT(FieldIconSvg, v))
}

// IconSvgLTE applies the LTE predicate on the "icon_svg" field.
func IconSvgLTE(v string) predicate.Protocol {
	return predicate.Protocol(sql.FieldLTE(FieldIconSvg, v))
}

// IconSvgContains applies the Contains predicate on the "icon_svg" field.
func IconSvgContains(v string) predicate.Protocol {
	return predicate.Protocol(sql.FieldContains(FieldIconSvg, v))
}

// IconSvgHasPrefix applies the HasPrefix predicate on the "icon_svg" field.
func IconSvgHasPrefix(v string) predicate.Protocol {
	return predicate.Protocol(sql.FieldHasPrefix(FieldIconSvg, v))
}

// IconSvgHasSuffix applies the HasSuffix predicate on the "icon_svg" field.
func IconSvgHasSuffix(v string) predicate.Protocol {
	return predicate.Protocol(sql.FieldHasSuffix(FieldIconSvg, v))
}

// IconSvgIsNil applies the IsNil predicate on the "icon_svg" field.
func IconSvgIsNil() predicate.Protocol {
	return predicate.Protocol(sql.FieldIsNull(FieldIconSvg))
}

// IconSvgNotNil applies the NotNil predicate on the "icon_svg" field.
func IconSvgNotNil() predicate.Protocol {
	return predicate.Protocol(sql.FieldNotNull(FieldIconSvg))
}

// IconSvgEqualFold applies the EqualFold predicate on the "icon_svg" field.
func IconSvgEqualFold(v string) predicate.Protocol {
	return predicate.Protocol(sql.FieldEqualFold(FieldIconSvg, v))
}

// IconSvgContainsFold applies the ContainsFold predicate on the "icon_svg" field.
func IconSvgContainsFold(v string) predicate.Protocol {
	return predicate.Protocol(sql.FieldContainsFold(FieldIconSvg, v))
}

// ThemeColorEQ applies the EQ predicate on the "theme_color" field.
func ThemeColorEQ(v string) predicate.Protocol {
	return predicate.Protocol(sql.FieldEQ(FieldThemeColor, v))
}

// ThemeColorNEQ applies the NEQ predicate on the "theme_color" field.
func ThemeColorNEQ(v string) predicate.Protocol {
	return predicate.Protocol(sql.FieldNEQ(FieldThemeColor, v))
}

// ThemeColorIn applies the In predicate on the "theme_color" field.
func ThemeColorIn(vs ...string) predicate.Protocol {
	return predicate.Protocol(sql.FieldIn(FieldThemeColor, vs...))
}

// ThemeColorNotIn applies the NotIn predicate on the "theme_color" field.
func ThemeColorNotIn(vs ...string) predicate.Protocol {
	return predicate.Protocol(sql.FieldNotIn(FieldThemeColor, vs...))
}

// ThemeColorGT applies the GT predicate on the "theme_color" field.
func ThemeColorGT(v string) predicate.Protocol {
	return predicate.Protocol(sql.FieldGT(FieldThemeColor, v))
}

// ThemeColorGTE applies the GTE predicate on the "theme_color" field.
func ThemeColorGTE(v string) predicate.Protocol {
	return predicate.Protocol(sql.FieldGTE(FieldThemeColor, v))
}

// ThemeColorLT applies the LT predicate on the "theme_color" field.
func ThemeColorLT(v string) predicate.Protocol {
	return predicate.Protocol(sql.FieldLT(FieldThemeColor, v))
}

// ThemeColorLTE applies the LTE predicate on the "theme_color" field.
func ThemeColorLTE(v string) predicate.Protocol {
	return predicate.Protocol(sql.FieldLTE(FieldThemeColor, v))
}

// ThemeColorContains applies the Contains predicate on the "theme_color" field.
func ThemeColorContains(v string) predicate.Protocol {
	return predicate.Protocol(sql.FieldContains(FieldThemeColor, v))
}

// ThemeColorHasPrefix applies the HasPrefix predicate on the "theme_color" field.
func ThemeColorHasPrefix(v string) predicate.Protocol {
	return predicate.Protocol(sql.FieldHasPrefix(FieldThemeColor, v))
}

// ThemeColorHasSuffix applies the HasSuffix predicate on the "theme_color" field.
func ThemeColorHasSuffix(v string) predicate.Protocol {
	return predicate.Protocol(sql.FieldHasSuffix(FieldThemeColor, v))
}

// ThemeColorEqualFold applies the EqualFold predicate on the "theme_color" field.
func ThemeColorEqualFold(v string) predicate.Protocol {
	return predicate.Protocol(sql.FieldEqualFold(FieldThemeColor, v))
}

// ThemeColorContainsFold applies the ContainsFold predicate on the "theme_color" field.
func ThemeColorContainsFold(v string) predicate.Protocol {
	return predicate.Protocol(sql.FieldContainsFold(FieldThemeColor, v))
}

// SortOrderEQ applies the EQ predicate on the "sort_order" field.
func SortOrderEQ(v int) predicate.Protocol {
	return predicate.Protocol(sql.FieldEQ(FieldSortOrder, v))
}

// SortOrderNEQ applies the NEQ predicate on the "sort_order" field.
func SortOrderNEQ(v int) predicate.Protocol {
	return predicate.Protocol(sql.FieldNEQ(FieldSortOrder, v))
}

// SortOrderIn applies the In predicate on the "sort_order" field.
func SortOrderIn(vs ...int) predicate.Protocol {
	return predicate.Protocol(sql.FieldIn(FieldSortOrder, vs...))
}

// SortOrderNotIn applies the NotIn predicate on the "sort_order" field.
func SortOrderNotIn(vs ...int) predicate.Protocol {
	return predicate.Protocol(sql.FieldNotIn(FieldSortOrder, vs...))
}

// SortOrderGT applies the GT predicate on the "sort_order" field.
func SortOrderGT(v int) predicate.Protocol {
	return predicate.Protocol(sql.FieldGT(FieldSortOrder, v))
}

// SortOrderGTE applies the GTE predicate on the "sort_order" field.
func SortOrderGTE(v int) predicate.Protocol {
	return predicate.Protocol(sql.FieldGTE(FieldSortOrder, v))
}

// SortOrderLT applies the LT predicate on the "sort_order" field.
func SortOrderLT(v int) predicate.Protocol {
	return predicate.Protocol(sql.FieldLT(FieldSortOrder, v))
}

// SortOrderLTE applies the LTE predicate on the "sort_order" field.
func SortOrderLTE(v int) predicate.Protocol {
	return predicate.Protocol(sql.FieldLTE(FieldSortOrder, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.Protocol {
	return predicate.Protocol(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.Protocol {
	return predicate.Protocol(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.Protocol {
	return predicate.Protocol(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.Protocol {
	return predicate.Protocol(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.Protocol {
	return predicate.Protocol(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.Protocol {
	return predicate.Protocol(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.Protocol {
	return predicate.Protocol(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.Protocol {
	return predicate.Protocol(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.Protocol {
	return predicate.Protocol(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.Protocol {
	return predicate.Protocol(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.Protocol {
	return predicate.Protocol(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.Protocol {
	return predicate.Protocol(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.Protocol {
	return predicate.Protocol(sql.FieldContainsFold(FieldStatus, v))
}

// HasGroups applies the HasEdge predicate on the "groups" edge.
func HasGroups() predicate.Protocol {
	return predicate.Protocol(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, GroupsTable, GroupsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGroupsWith applies the HasEdge predicate on the "groups" edge with a given conditions (other predicates).
func HasGroupsWith(preds ...predicate.Group) predicate.Protocol {
	return predicate.Protocol(func(s *sql.Selector) {
		step := newGroupsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Protocol) predicate.Protocol {
	return predicate.Protocol(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Protocol) predicate.Protocol {
	return predicate.Protocol(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Protocol) predicate.Protocol {
	return predicate.Protocol(sql.NotPredicates(p))
}
