// Code generated by ent, DO NOT EDIT.

package plugin

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the plugin type in the database.
	Label = "plugin"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldVersion holds the string denoting the version field in the database.
	FieldVersion = "version"
	// FieldAPIVersion holds the string denoting the api_version field in the database.
	FieldAPIVersion = "api_version"
	// FieldState holds the string denoting the state field in the database.
	FieldState = "state"
	// FieldInstalledAt holds the string denoting the installed_at field in the database.
	FieldInstalledAt = "installed_at"
	// FieldLastEnabledAt holds the string denoting the last_enabled_at field in the database.
	FieldLastEnabledAt = "last_enabled_at"
	// FieldDeclaredTables holds the string denoting the declared_tables field in the database.
	FieldDeclaredTables = "declared_tables"
	// FieldMetaSnapshot holds the string denoting the meta_snapshot field in the database.
	FieldMetaSnapshot = "meta_snapshot"
	// Table holds the table name of the plugin in the database.
	Table = "plugins"
)

// Columns holds all SQL columns for plugin fields.
var Columns = []string{
	FieldID,
	FieldVersion,
	FieldAPIVersion,
	FieldState,
	FieldInstalledAt,
	FieldLastEnabledAt,
	FieldDeclaredTables,
	FieldMetaSnapshot,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// VersionValidator is a validator for the "version" field. It is called by the builders before save.
	VersionValidator func(string) error
	// APIVersionValidator is a validator for the "api_version" field. It is called by the builders before save.
	APIVersionValidator func(string) error
	// DefaultInstalledAt holds the default value on creation for the "installed_at" field.
	DefaultInstalledAt func() time.Time
	// DefaultDeclaredTables holds the default value on creation for the "declared_tables" field.
	DefaultDeclaredTables []string
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// State defines the type for the "state" enum field.
type State string

// StateInstalled is the default value of the State enum.
const DefaultState = StateInstalled

// State values.
const (
	StateInstalled   State = "installed"
	StateDisabled    State = "disabled"
	StateEnabled     State = "enabled"
	StateUninstalled State = "uninstalled"
)

func (s State) String() string {
	return string(s)
}

// StateValidator is a validator for the "state" field enum values. It is called by the builders before save.
func StateValidator(s State) error {
	switch s {
	case StateInstalled, StateDisabled, StateEnabled, StateUninstalled:
		return nil
	default:
		return fmt.Errorf("plugin: invalid enum value for state field: %q", s)
	}
}

// OrderOption defines the ordering options for the Plugin queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByVersion orders the results by the version field.
func ByVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVersion, opts...).ToFunc()
}

// ByAPIVersion orders the results by the api_version field.
func ByAPIVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPIVersion, opts...).ToFunc()
}

// ByState orders the results by the state field.
func ByState(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldState, opts...).ToFunc()
}

// ByInstalledAt orders the results by the installed_at field.
func ByInstalledAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInstalledAt, opts...).ToFunc()
}

// ByLastEnabledAt orders the results by the last_enabled_at field.
func ByLastEnabledAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastEnabledAt, opts...).ToFunc()
}
