// Code generated by ent, DO NOT EDIT.

package plugin

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Plugin {
	return predicate.Plugin(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Plugin {
	return predicate.Plugin(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Plugin {
	return predicate.Plugin(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Plugin {
	return predicate.Plugin(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Plugin {
	return predicate.Plugin(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Plugin {
	return predicate.Plugin(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Plugin {
	return predicate.Plugin(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Plugin {
	return predicate.Plugin(sql.FieldContainsFold(FieldID, id))
}

// Version applies equality check predicate on the "version" field. It's identical to VersionEQ.
func Version(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldVersion, v))
}

// APIVersion applies equality check predicate on the "api_version" field. It's identical to APIVersionEQ.
func APIVersion(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldAPIVersion, v))
}

// InstalledAt applies equality check predicate on the "installed_at" field. It's identical to InstalledAtEQ.
func InstalledAt(v time.Time) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldInstalledAt, v))
}

// LastEnabledAt applies equality check predicate on the "last_enabled_at" field. It's identical to LastEnabledAtEQ.
func LastEnabledAt(v time.Time) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldLastEnabledAt, v))
}

// VersionEQ applies the EQ predicate on the "version" field.
func VersionEQ(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldVersion, v))
}

// VersionNEQ applies the NEQ predicate on the "version" field.
func VersionNEQ(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldNEQ(FieldVersion, v))
}

// VersionIn applies the In predicate on the "version" field.
func VersionIn(vs ...string) predicate.Plugin {
	return predicate.Plugin(sql.FieldIn(FieldVersion, vs...))
}

// VersionNotIn applies the NotIn predicate on the "version" field.
func VersionNotIn(vs ...string) predicate.Plugin {
	return predicate.Plugin(sql.FieldNotIn(FieldVersion, vs...))
}

// VersionGT applies the GT predicate on the "version" field.
func VersionGT(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldGT(FieldVersion, v))
}

// VersionGTE applies the GTE predicate on the "version" field.
func VersionGTE(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldGTE(FieldVersion, v))
}

// VersionLT applies the LT predicate on the "version" field.
func VersionLT(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldLT(FieldVersion, v))
}

// VersionLTE applies the LTE predicate on the "version" field.
func VersionLTE(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldLTE(FieldVersion, v))
}

// VersionContains applies the Contains predicate on the "version" field.
func VersionContains(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldContains(FieldVersion, v))
}

// VersionHasPrefix applies the HasPrefix predicate on the "version" field.
func VersionHasPrefix(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldHasPrefix(FieldVersion, v))
}

// VersionHasSuffix applies the HasSuffix predicate on the "version" field.
func VersionHasSuffix(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldHasSuffix(FieldVersion, v))
}

// VersionEqualFold applies the EqualFold predicate on the "version" field.
func VersionEqualFold(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEqualFold(FieldVersion, v))
}

// VersionContainsFold applies the ContainsFold predicate on the "version" field.
func VersionContainsFold(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldContainsFold(FieldVersion, v))
}

// APIVersionEQ applies the EQ predicate on the "api_version" field.
func APIVersionEQ(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldAPIVersion, v))
}

// APIVersionNEQ applies the NEQ predicate on the "api_version" field.
func APIVersionNEQ(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldNEQ(FieldAPIVersion, v))
}

// APIVersionIn applies the In predicate on the "api_version" field.
func APIVersionIn(vs ...string) predicate.Plugin {
	return predicate.Plugin(sql.FieldIn(FieldAPIVersion, vs...))
}

// APIVersionNotIn applies the NotIn predicate on the "api_version" field.
func APIVersionNotIn(vs ...string) predicate.Plugin {
	return predicate.Plugin(sql.FieldNotIn(FieldAPIVersion, vs...))
}

// APIVersionGT applies the GT predicate on the "api_version" field.
func APIVersionGT(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldGT(FieldAPIVersion, v))
}

// APIVersionGTE applies the GTE predicate on the "api_version" field.
func APIVersionGTE(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldGTE(FieldAPIVersion, v))
}

// APIVersionLT applies the LT predicate on the "api_version" field.
func APIVersionLT(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldLT(FieldAPIVersion, v))
}

// APIVersionLTE applies the LTE predicate on the "api_version" field.
func APIVersionLTE(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldLTE(FieldAPIVersion, v))
}

// APIVersionContains applies the Contains predicate on the "api_version" field.
func APIVersionContains(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldContains(FieldAPIVersion, v))
}

// APIVersionHasPrefix applies the HasPrefix predicate on the "api_version" field.
func APIVersionHasPrefix(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldHasPrefix(FieldAPIVersion, v))
}

// APIVersionHasSuffix applies the HasSuffix predicate on the "api_version" field.
func APIVersionHasSuffix(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldHasSuffix(FieldAPIVersion, v))
}

// APIVersionEqualFold applies the EqualFold predicate on the "api_version" field.
func APIVersionEqualFold(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEqualFold(FieldAPIVersion, v))
}

// APIVersionContainsFold applies the ContainsFold predicate on the "api_version" field.
func APIVersionContainsFold(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldContainsFold(FieldAPIVersion, v))
}

// StateEQ applies the EQ predicate on the "state" field.
func StateEQ(v State) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldState, v))
}

// StateNEQ applies the NEQ predicate on the "state" field.
func StateNEQ(v State) predicate.Plugin {
	return predicate.Plugin(sql.FieldNEQ(FieldState, v))
}

// StateIn applies the In predicate on the "state" field.
func StateIn(vs ...State) predicate.Plugin {
	return predicate.Plugin(sql.FieldIn(FieldState, vs...))
}

// StateNotIn applies the NotIn predicate on the "state" field.
func StateNotIn(vs ...State) predicate.Plugin {
	return predicate.Plugin(sql.FieldNotIn(FieldState, vs...))
}

// InstalledAtEQ applies the EQ predicate on the "installed_at" field.
func InstalledAtEQ(v time.Time) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldInstalledAt, v))
}

// InstalledAtNEQ applies the NEQ predicate on the "installed_at" field.
func InstalledAtNEQ(v time.Time) predicate.Plugin {
	return predicate.Plugin(sql.FieldNEQ(FieldInstalledAt, v))
}

// InstalledAtIn applies the In predicate on the "installed_at" field.
func InstalledAtIn(vs ...time.Time) predicate.Plugin {
	return predicate.Plugin(sql.FieldIn(FieldInstalledAt, vs...))
}

// InstalledAtNotIn applies the NotIn predicate on the "installed_at" field.
func InstalledAtNotIn(vs ...time.Time) predicate.Plugin {
	return predicate.Plugin(sql.FieldNotIn(FieldInstalledAt, vs...))
}

// InstalledAtGT applies the GT predicate on the "installed_at" field.
func InstalledAtGT(v time.Time) predicate.Plugin {
	return predicate.Plugin(sql.FieldGT(FieldInstalledAt, v))
}

// InstalledAtGTE applies the GTE predicate on the "installed_at" field.
func InstalledAtGTE(v time.Time) predicate.Plugin {
	return predicate.Plugin(sql.FieldGTE(FieldInstalledAt, v))
}

// InstalledAtLT applies the LT predicate on the "installed_at" field.
func InstalledAtLT(v time.Time) predicate.Plugin {
	return predicate.Plugin(sql.FieldLT(FieldInstalledAt, v))
}

// InstalledAtLTE applies the LTE predicate on the "installed_at" field.
func InstalledAtLTE(v time.Time) predicate.Plugin {
	return predicate.Plugin(sql.FieldLTE(FieldInstalledAt, v))
}

// LastEnabledAtEQ applies the EQ predicate on the "last_enabled_at" field.
func LastEnabledAtEQ(v time.Time) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldLastEnabledAt, v))
}

// LastEnabledAtNEQ applies the NEQ predicate on the "last_enabled_at" field.
func LastEnabledAtNEQ(v time.Time) predicate.Plugin {
	return predicate.Plugin(sql.FieldNEQ(FieldLastEnabledAt, v))
}

// LastEnabledAtIn applies the In predicate on the "last_enabled_at" field.
func LastEnabledAtIn(vs ...time.Time) predicate.Plugin {
	return predicate.Plugin(sql.FieldIn(FieldLastEnabledAt, vs...))
}

// LastEnabledAtNotIn applies the NotIn predicate on the "last_enabled_at" field.
func LastEnabledAtNotIn(vs ...time.Time) predicate.Plugin {
	return predicate.Plugin(sql.FieldNotIn(FieldLastEnabledAt, vs...))
}

// LastEnabledAtGT applies the GT predicate on the "last_enabled_at" field.
func LastEnabledAtGT(v time.Time) predicate.Plugin {
	return predicate.Plugin(sql.FieldGT(FieldLastEnabledAt, v))
}

// LastEnabledAtGTE applies the GTE predicate on the "last_enabled_at" field.
func LastEnabledAtGTE(v time.Time) predicate.Plugin {
	return predicate.Plugin(sql.FieldGTE(FieldLastEnabledAt, v))
}

// LastEnabledAtLT applies the LT predicate on the "last_enabled_at" field.
func LastEnabledAtLT(v time.Time) predicate.Plugin {
	return predicate.Plugin(sql.FieldLT(FieldLastEnabledAt, v))
}

// LastEnabledAtLTE applies the LTE predicate on the "last_enabled_at" field.
func LastEnabledAtLTE(v time.Time) predicate.Plugin {
	return predicate.Plugin(sql.FieldLTE(FieldLastEnabledAt, v))
}

// LastEnabledAtIsNil applies the IsNil predicate on the "last_enabled_at" field.
func LastEnabledAtIsNil() predicate.Plugin {
	return predicate.Plugin(sql.FieldIsNull(FieldLastEnabledAt))
}

// LastEnabledAtNotNil applies the NotNil predicate on the "last_enabled_at" field.
func LastEnabledAtNotNil() predicate.Plugin {
	return predicate.Plugin(sql.FieldNotNull(FieldLastEnabledAt))
}

// MetaSnapshotIsNil applies the IsNil predicate on the "meta_snapshot" field.
func MetaSnapshotIsNil() predicate.Plugin {
	return predicate.Plugin(sql.FieldIsNull(FieldMetaSnapshot))
}

// MetaSnapshotNotNil applies the NotNil predicate on the "meta_snapshot" field.
func MetaSnapshotNotNil() predicate.Plugin {
	return predicate.Plugin(sql.FieldNotNull(FieldMetaSnapshot))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Plugin) predicate.Plugin {
	return predicate.Plugin(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Plugin) predicate.Plugin {
	return predicate.Plugin(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Plugin) predicate.Plugin {
	return predicate.Plugin(sql.NotPredicates(p))
}
